save2id = {

    "research-example-1": ("main", "1-1"),
    "research-tutorial-1": ("main", "1-2"),
    "research-tutorial-1point5": ("main", "1-3"),
    "research-example-2": ("main", "1-4"),
    "research-tutorial-2": ("main", "1-5"),
    "research-tutorial-3": ("main", "1-6"),

    "research-tutorial-4": ("main", "2-1"),
    "research-tutorial-5": ("main", "2-2"),
    "research-tutorial-6": ("main", "2-3"),
    "production-tutorial-1": ("main", "2-4"),
    "production-tutorial-2": ("main", "2-5"),
    "production-tutorial-3": ("main", "2-6"),

    "bonding-2": ("main", "3-1"),
    "bonding-3": ("main", "3-2"),
    "bonding-4": ("main", "3-3"),
    "bonding-6": ("main", "3-4"),
    "bonding-7": ("main", "3-5"),
    "bonding-boss": ('main', '3-6'),
    "bonding-5": ("main", "3-C"),

    "sensing-1": ("main", "4-1"),
    "sensing-2": ("main", "4-2"),
    "sensing-3": ("main", "4-3"),
    "sensing-4": ("main", "4-4"),
    "sensing-5": ("main", "4-5"),
    "sensing-boss": ('main', '4-6'),
    "sensing-6": ("main", "4-C"),
    
    "fusion-1": ("main", "5-1"),
    "fusion-2": ("main", "5-2"),
    "fusion-3": ("main", "5-3"),
    "fusion-5": ("main", "5-4"),
    "fusion-boss": ('main', '5-5'),
    "fusion-6": ("main", "5-C"),

    "mining-2": ("main", "6-1"),
    "mining-3": ("main", "6-2"),
    "mining-7": ("main", "6-3"),
    "mining-1": ("main", "6-4"),
    "mining-5": ("main", "6-6"),
    "mining-4": ("main", "6-7"),
    "mining-boss": ('main', '6-5'),
    "mining-6": ("main", "6-C"),

    "research-1": ("main", "7-1"),
    "research-3": ("main", "7-2"),
    "research-6": ("main", "7-3"),
    "research-5": ("main", "7-4"),
    "research-2": ("main", "7-5"),
    "research-boss": ('main', '7-6'),

    "organic-1": ("main", "8-1"),
    "organic-2": ("main", "8-2"),
    "organic-3": ("main", "8-3"),
    "organic-5": ("main", "8-5a"),
    "organic-6": ("main", "8-5b"),
    "organic-boss": ('main', '8-4'),

    "warp-boss": ('main', '9-1'),


    "tf2-1": ("tf2", "TF2-1"),
    "tf2-2": ("tf2", "TF2-2"),
    "tf2-3": ("tf2", "TF2-3"),


    "quantum-1": ("63corvi", "1"),
    "quantum-2": ("63corvi", "2"),
    "quantum-4": ("63corvi", "3"),
    "quantum-3": ("63corvi", "4"),
    "quantum-5": ("63corvi", "5"),
    "quantum-6": ("63corvi", "6"),
    "quantum-boss": ('63corvi', '7'),


    "published-1-1": ("researchnet", "1-1-1"),
    "published-1-2": ("researchnet", "1-1-2"),
    "published-1-3": ("researchnet", "1-1-3"),
    "published-2-1": ("researchnet", "1-2-1"),
    "published-2-2": ("researchnet", "1-2-2"),
    "published-2-3": ("researchnet", "1-2-3"),
    "published-3-1": ("researchnet", "1-3-1"),
    "published-3-2": ("researchnet", "1-3-2"),
    "published-3-3": ("researchnet", "1-3-3"),
    "published-4-1": ("researchnet", "1-4-1"),
    "published-4-2": ("researchnet", "1-4-2"),
    "published-4-3": ("researchnet", "1-4-3"),
    "published-5-1": ("researchnet", "1-5-1"),
    "published-5-2": ("researchnet", "1-5-2"),
    "published-5-3": ("researchnet", "1-5-3"),
    "published-6-1": ("researchnet", "1-6-1"),
    "published-6-2": ("researchnet", "1-6-2"),
    "published-6-3": ("researchnet", "1-6-3"),
    "published-7-1": ("researchnet", "1-7-1"),
    "published-7-2": ("researchnet", "1-7-2"),
    "published-7-3": ("researchnet", "1-7-3"),
    "published-8-1": ("researchnet", "1-8-1"),
    "published-8-2": ("researchnet", "1-8-2"),
    "published-8-3": ("researchnet", "1-8-3"),
    "published-9-1": ("researchnet", "1-9-1"),
    "published-9-2": ("researchnet", "1-9-2"),
    "published-9-3": ("researchnet", "1-9-3"),
    "published-10-1": ("researchnet", "1-10-1"),
    "published-10-2": ("researchnet", "1-10-2"),
    "published-10-3": ("researchnet", "1-10-3"),
    "published-11-1": ("researchnet", "1-11-1"),
    "published-11-2": ("researchnet", "1-11-2"),
    "published-11-3b": ("researchnet", "1-11-3"),
    "published-12-1": ("researchnet", "1-12-1"),
    "published-12-2": ("researchnet", "1-12-2"),
    "published-12-3": ("researchnet", "1-12-3"),

    "published-13-1": ("researchnet", "2-1-1"),
    "published-13-2": ("researchnet", "2-1-2"),
    "published-13-3": ("researchnet", "2-1-3"),
    "published-14-1": ("researchnet", "2-2-1"),
    "published-14-2": ("researchnet", "2-2-2"),
    "published-14-3": ("researchnet", "2-2-3"),
    "published-15-1": ("researchnet", "2-3-1"),
    "published-15-2": ("researchnet", "2-3-2"),
    "published-15-3": ("researchnet", "2-3-3"),
    "published-16-1": ("researchnet", "2-4-1"),
    "published-16-2": ("researchnet", "2-4-2"),
    "published-16-3": ("researchnet", "2-4-3"),
    "published-17-1": ("researchnet", "2-5-1"),
    "published-17-2": ("researchnet", "2-5-2"),
    "published-17-3": ("researchnet", "2-5-3"),
    "published-18-1": ("researchnet", "2-6-1"),
    "published-18-2": ("researchnet", "2-6-2"),
    "published-18-3": ("researchnet", "2-6-3"),
    "published-19-1": ("researchnet", "2-7-1"),
    "published-19-2": ("researchnet", "2-7-2"),
    "published-19-3": ("researchnet", "2-7-3"),
    "published-20-1": ("researchnet", "2-8-1"),
    "published-20-2": ("researchnet", "2-8-2"),
    "published-20-3": ("researchnet", "2-8-3"),
    "published-21-1": ("researchnet", "2-9-1"),
    "published-21-2": ("researchnet", "2-9-2"),
    "published-21-3": ("researchnet", "2-9-3"),
    "published-22-1": ("researchnet", "2-10-1"),
    "published-22-2": ("researchnet", "2-10-2"),
    "published-22-3": ("researchnet", "2-10-3"),
    "published-23-1": ("researchnet", "2-11-1"),
    "published-23-2": ("researchnet", "2-11-2"),
    "published-23-3": ("researchnet", "2-11-3"),
    "published-24-1": ("researchnet", "2-12-1"),
    "published-24-2": ("researchnet", "2-12-2"),
    "published-24-3": ("researchnet", "2-12-3"),

    "published-25-1": ("researchnet", "3-1-1"),
    "published-25-2": ("researchnet", "3-1-2"),
    "published-25-3": ("researchnet", "3-1-3"),
    "published-26-1": ("researchnet", "3-2-1"),
    "published-26-2": ("researchnet", "3-2-2"),
    "published-26-3": ("researchnet", "3-2-3"),
    "published-27-1": ("researchnet", "3-3-1"),
    "published-27-2": ("researchnet", "3-3-2"),
    "published-27-3": ("researchnet", "3-3-3"),
    "published-28-1": ("researchnet", "3-4-1"),
    "published-28-2": ("researchnet", "3-4-2"),
    "published-28-3": ("researchnet", "3-4-3"),
    "published-29-1": ("researchnet", "3-5-1"),
    "published-29-2": ("researchnet", "3-5-2"),
    "published-29-3": ("researchnet", "3-5-3"),
    "published-30-1": ("researchnet", "3-6-1"),
    "published-30-2": ("researchnet", "3-6-2"),
    "published-30-3": ("researchnet", "3-6-3"),
    "published-31-1": ("researchnet", "3-7-1"),
    "published-31-2": ("researchnet", "3-7-2"),
    "published-31-3": ("researchnet", "3-7-3"),
    "published-32-1": ("researchnet", "3-8-1"),
    "published-32-2": ("researchnet", "3-8-2"),
    "published-32-3": ("researchnet", "3-8-3"),
    "published-33-1": ("researchnet", "3-9-1"),
    "published-33-2": ("researchnet", "3-9-2"),
    "published-33-3": ("researchnet", "3-9-3"),
    "published-34-1": ("researchnet", "3-10-1"),
    "published-34-2": ("researchnet", "3-10-2"),
    "published-34-3": ("researchnet", "3-10-3"),
    "published-35-1": ("researchnet", "3-11-1"),
    "published-35-2": ("researchnet", "3-11-2"),
    "published-35-3": ("researchnet", "3-11-3"),
    "published-36-1": ("researchnet", "3-12-1"),
    "published-36-2": ("researchnet", "3-12-2"),
    "published-36-3": ("researchnet", "3-12-3"),

    "published-37-1": ("researchnet", "4-1-1"),
    "published-37-2": ("researchnet", "4-1-2"),
    "published-37-3": ("researchnet", "4-1-3"),
    "published-38-1": ("researchnet", "4-2-1"),
    "published-38-2": ("researchnet", "4-2-2"),
    "published-38-3": ("researchnet", "4-2-3"),
    "published-39-1": ("researchnet", "4-3-1"),
    "published-39-2": ("researchnet", "4-3-2"),
    "published-39-3": ("researchnet", "4-3-3"),
    "published-40-1": ("researchnet", "4-4-1"),
    "published-40-2": ("researchnet", "4-4-2"),
    "published-40-3": ("researchnet", "4-4-3"),
    "published-41-1": ("researchnet", "4-5-1"),
    "published-41-2": ("researchnet", "4-5-2"),
    "published-41-3": ("researchnet", "4-5-3"),
    "published-42-1": ("researchnet", "4-6-1"),
    "published-42-2": ("researchnet", "4-6-2"),
    "published-42-3": ("researchnet", "4-6-3"),
    "published-43-1": ("researchnet", "4-7-1"),
    "published-43-2": ("researchnet", "4-7-2"),
    "published-43-3": ("researchnet", "4-7-3"),
    "published-44-1": ("researchnet", "4-8-1"),
    "published-44-2": ("researchnet", "4-8-2"),
    "published-44-3": ("researchnet", "4-8-3"),
    "published-45-1": ("researchnet", "4-9-1"),
    "published-45-2": ("researchnet", "4-9-2"),
    "published-45-3": ("researchnet", "4-9-3"),
    "published-46-1": ("researchnet", "4-10-1"),
    "published-46-2": ("researchnet", "4-10-2"),
    "published-46-3": ("researchnet", "4-10-3"),
    "published-47-1": ("researchnet", "4-11-1"),
    "published-47-2": ("researchnet", "4-11-2"),
    "published-47-3": ("researchnet", "4-11-3"),
    "published-48-1": ("researchnet", "4-12-1"),
    "published-48-2": ("researchnet", "4-12-2"),
    "published-48-3": ("researchnet", "4-12-3"),

    "published-49-1": ("researchnet", "5-1-1"),
    "published-49-2": ("researchnet", "5-1-2"),
    "published-49-3": ("researchnet", "5-1-3"),
    "published-50-1": ("researchnet", "5-2-1"),
    "published-50-2": ("researchnet", "5-2-2"),
    "published-50-3": ("researchnet", "5-2-3"),
    "published-51-1": ("researchnet", "5-3-1"),
    "published-51-2": ("researchnet", "5-3-2"),
    "published-51-3": ("researchnet", "5-3-3"),
    "published-52-1": ("researchnet", "5-4-1"),
    "published-52-2": ("researchnet", "5-4-2"),
    "published-52-3": ("researchnet", "5-4-3"),
    "published-53-1": ("researchnet", "5-5-1"),
    "published-53-2": ("researchnet", "5-5-2"),
    "published-53-3": ("researchnet", "5-5-3"),
    "published-54-1": ("researchnet", "5-6-1"),
    "published-54-2": ("researchnet", "5-6-2"),
    "published-54-3": ("researchnet", "5-6-3"),
    "published-55-1": ("researchnet", "5-7-1"),
    "published-55-2": ("researchnet", "5-7-2"),
    "published-55-3": ("researchnet", "5-7-3"),
    "published-56-1": ("researchnet", "5-8-1"),
    "published-56-2": ("researchnet", "5-8-2"),
    "published-56-3": ("researchnet", "5-8-3"),
    "published-57-1": ("researchnet", "5-9-1"),
    "published-57-2": ("researchnet", "5-9-2"),
    "published-57-3": ("researchnet", "5-9-3"),
    "published-58-1": ("researchnet", "5-10-1"),
    "published-58-2": ("researchnet", "5-10-2"),
    "published-58-3": ("researchnet", "5-10-3"),
    "published-59-1": ("researchnet", "5-11-1"),
    "published-59-2": ("researchnet", "5-11-2"),
    "published-59-3": ("researchnet", "5-11-3"),
    "published-60-1": ("researchnet", "5-12-1"),
    "published-60-2": ("researchnet", "5-12-2"),
    "published-60-3": ("researchnet", "5-12-3"),

    "published-61-1": ("researchnet", "6-1-1"),
    "published-61-2": ("researchnet", "6-1-2"),
    "published-61-3": ("researchnet", "6-1-3"),
    "published-62-1": ("researchnet", "6-2-1"),
    "published-62-2": ("researchnet", "6-2-2"),
    "published-62-3": ("researchnet", "6-2-3"),
    "published-63-1": ("researchnet", "6-3-1"),
    "published-63-2": ("researchnet", "6-3-2"),
    "published-63-3": ("researchnet", "6-3-3"),
    "published-64-1": ("researchnet", "6-4-1"),
    "published-64-2": ("researchnet", "6-4-2"),
    "published-64-3": ("researchnet", "6-4-3"),

    "published-71-1": ("researchnet", "7-1-1"),
    "published-71-2": ("researchnet", "7-1-2"),
    "published-71-3": ("researchnet", "7-1-3"),
    "published-72-1": ("researchnet", "7-2-1"),
    "published-72-2": ("researchnet", "7-2-2"),
    "published-72-3": ("researchnet", "7-2-3"),
    "published-73-1": ("researchnet", "7-3-1"),
    "published-73-2": ("researchnet", "7-3-2"),
    "published-73-3": ("researchnet", "7-3-3"),
    "published-74-1": ("researchnet", "7-4-1"),
    "published-74-2": ("researchnet", "7-4-2"),
    "published-74-3": ("researchnet", "7-4-3"),
    "published-75-1": ("researchnet", "7-5-1"),
    "published-75-2": ("researchnet", "7-5-2"),
    "published-75-3": ("researchnet", "7-5-3"),
    "published-76-1": ("researchnet", "7-6-1"),
    "published-76-2": ("researchnet", "7-6-2"),
    "published-76-3": ("researchnet", "7-6-3"),

    "published-77-1": ("researchnet", "8-1-1"),
    "published-77-2": ("researchnet", "8-1-2"),
    "published-77-3": ("researchnet", "8-1-3"),
    "published-78-1": ("researchnet", "8-2-1"),
    "published-78-2": ("researchnet", "8-2-2"),
    "published-78-3": ("researchnet", "8-2-3"),
    "published-79-1": ("researchnet", "8-3-1"),
    "published-79-2": ("researchnet", "8-3-2"),
    "published-79-3": ("researchnet", "8-3-3"),
    "published-80-1": ("researchnet", "8-4-1"),
    "published-80-2": ("researchnet", "8-4-2"),
    "published-80-3": ("researchnet", "8-4-3"),
    "published-81-1": ("researchnet", "8-5-1"),
    "published-81-2": ("researchnet", "8-5-2"),
    "published-81-3": ("researchnet", "8-5-3"),
    "published-82-1": ("researchnet", "8-6-1"),
    "published-82-2": ("researchnet", "8-6-2"),
    "published-82-3": ("researchnet", "8-6-3"),
    "published-83-1": ("researchnet", "8-7-1"),
    "published-83-2": ("researchnet", "8-7-2"),
    "published-83-3": ("researchnet", "8-7-3"),
    "published-84-1": ("researchnet", "8-8-1"),
    "published-84-2": ("researchnet", "8-8-2"),
    "published-84-3": ("researchnet", "8-8-3"),
    "published-85-1": ("researchnet", "8-9-1"),
    "published-85-2": ("researchnet", "8-9-2"),
    "published-85-3": ("researchnet", "8-9-3"),
    "published-86-1": ("researchnet", "8-10-1"),
    "published-86-2": ("researchnet", "8-10-2"),
    "published-86-3": ("researchnet", "8-10-3"),
    "published-87-1": ("researchnet", "8-11-1"),
    "published-87-2": ("researchnet", "8-11-2"),
    "published-87-3": ("researchnet", "8-11-3"),
    "published-88-1": ("researchnet", "8-12-1"),
    "published-88-2": ("researchnet", "8-12-2"),
    "published-88-3": ("researchnet", "8-12-3"),
    "published-89-1": ("researchnet", "8-13-1"),
    "published-89-2": ("researchnet", "8-13-2"),
    "published-89-3": ("researchnet", "8-13-3"),
    "published-90-1": ("researchnet", "8-14-1"),
    "published-90-2": ("researchnet", "8-14-2"),
    "published-90-3": ("researchnet", "8-14-3"),
    "published-91-1": ("researchnet", "8-15-1"),
    "published-91-2": ("researchnet", "8-15-2"),
    "published-91-3": ("researchnet", "8-15-3"),

}

id2name = {

    ("main", "1-1"): "Of Pancakes and Spaceships",
    ("main", "1-2"): "Slightly Different",
    ("main", "1-3"): "Crossover",
    ("main", "1-4"): "An Introduction to Bonding",
    ("main", "1-5"): "A Brief History of SpaceChem",
    ("main", "1-6"): "Removing Bonds",

    ("main", "2-1"): "Double Bonds",
    ("main", "2-2"): "Best Left Unanswered",
    ("main", "2-3"): "Multiple Outputs",
    ("main", "2-4"): "An Introduction to Pipelines",
    ("main", "2-5"): "There's Something in the Fishcake",
    ("main", "2-6"): "Sleepless on Sernimir IV",

    ("main", "3-1"): "Every Day is the First Day",
    ("main", "3-2"): "It Takes Three",
    ("main", "3-3"): "Split Before Bonding",
    ("main", "3-4"): "Settling into the Routine",
    ("main", "3-5"): "Nothing Works",
    ('main', '3-6'): "A Most Unfortunate Malfunction",
    ("main", "3-C"): "Challenge: In-Place Swap",

    ("main", "4-1"): "An Introduction to Sensing",
    ("main", "4-2"): "Prelude to a Migraine",
    ("main", "4-3"): "Random Oxides",
    ("main", "4-4"): "No Ordinary Headache",
    ("main", "4-5"): "No Thanks Necessary",
    ('main', '4-6'): "No Need for Introductions",
    ("main", "4-C"): "Challenge: Going Green",

    ("main", "5-1"): "Ice to Meet You",
    ("main", "5-2"): "Under the Ice",
    ("main", "5-3"): "Unknown Sender",
    ("main", "5-4"): "Falling",
    ('main', '5-5'): "Exploding Head Syndrome",
    ("main", "5-C"): "Challenge: Applied Fusion",

    ("main", "6-1"): "Like a Boss",
    ("main", "6-2"): "Sacré Bleu!",
    ("main", "6-3"): "The Plot Thickens",
    ("main", "6-4"): "Danger Zone",
    ("main", "6-6"): "Molecular Foundry",
    ("main", "6-7"): "Gas Works Park",
    ('main', '6-5'): "More than Machine",
    ("main", "6-C"): "Challenge: KOHCTPYKTOP",

    ("main", "7-1"): "The Blue Danube",
    ("main", "7-2"): "No Stomach for Lunch",
    ("main", "7-3"): "No Employment Record Found",
    ("main", "7-4"): "Right All Along",
    ("main", "7-5"): "Accidents Happen",
    ('main', '7-6'): "Don't Fear the Reaper",

    ("main", "8-1"): "Special Assignment",
    ("main", "8-2"): "Suspicious Behavior",
    ("main", "8-3"): "I Told You So",
    ("main", "8-5a"): "Ω-Pseudoethyne",
    ("main", "8-5b"): "Σ-Ethylene",
    ('main', '8-4'): "Freedom of Choice",

    ('main', '9-1'): "End of the Line",


    ("tf2", "TF2-1"): "Moustachium 602",
    ("tf2", "TF2-2"): "Moustachium 604",
    ("tf2", "TF2-3"): "Moustachium 608",


    ("63corvi", "1"): "QT-1",
    ("63corvi", "2"): "QT-2",
    ("63corvi", "3"): "Teleporters",
    ("63corvi", "4"): "QT-3",
    ("63corvi", "5"): "QT-4",
    ("63corvi", "6"): "Precursor Compounds",
    ('63corvi', '7'): "Collapsar",


    ("researchnet", "1-1-1"): "Tunnels I",
    ("researchnet", "1-1-2"): "Tunnels II",
    ("researchnet", "1-1-3"): "Tunnels III",
    ("researchnet", "1-2-1"): "Fission I",
    ("researchnet", "1-2-2"): "Fission II",
    ("researchnet", "1-2-3"): "Fission III",
    ("researchnet", "1-3-1"): "Chloroform",
    ("researchnet", "1-3-2"): "Cycloaddition",
    ("researchnet", "1-3-3"): "KOHCTPYKTOP++",
    ("researchnet", "1-4-1"): "Quantum Decomposition",
    ("researchnet", "1-4-2"): "Propane Accessories",
    ("researchnet", "1-4-3"): "Benzoic Acid",
    ("researchnet", "1-5-1"): "Electrophilic Addition",
    ("researchnet", "1-5-2"): "Diethyl Ether",
    ("researchnet", "1-5-3"): "2-Hexene",
    ("researchnet", "1-6-1"): "Mazeite'",
    ("researchnet", "1-6-2"): "Silica",
    ("researchnet", "1-6-3"): "Galvanization",
    ("researchnet", "1-7-1"): "Industrial Methanol",
    ("researchnet", "1-7-2"): "Glyoxylic Acid",
    ("researchnet", "1-7-3"): "Bioplastic",
    ("researchnet", "1-8-1"): "Chlorination",
    ("researchnet", "1-8-2"): "Sulfuric Acid",
    ("researchnet", "1-8-3"): "Bad Times",
    ("researchnet", "1-9-1"): "Friedel-Crafts",
    ("researchnet", "1-9-2"): "Wöhler Synthesis",
    ("researchnet", "1-9-3"): "Diels-Alder",
    ("researchnet", "1-10-1"): "Bad Times, Part II",
    ("researchnet", "1-10-2"): "Freon",
    ("researchnet", "1-10-3"): "Benzene Derivation",
    ("researchnet", "1-11-1"): "Portland Cement",
    ("researchnet", "1-11-2"): "Solder Coarsening",
    ("researchnet", "1-11-3"): "Graphene",
    ("researchnet", "1-12-1"): "The Big Cleanup",
    ("researchnet", "1-12-2"): "Going Green Part II",
    ("researchnet", "1-12-3"): "Waste Treatment",

    ("researchnet", "2-1-1"): "Pyridine",
    ("researchnet", "2-1-2"): "Breakdown",
    ("researchnet", "2-1-3"): "Vitamin B3",
    ("researchnet", "2-2-1"): "PVC",
    ("researchnet", "2-2-2"): "PVA",
    ("researchnet", "2-2-3"): "Naphthalene",
    ("researchnet", "2-3-1"): "Anthraquinone",
    ("researchnet", "2-3-2"): "Soap",
    ("researchnet", "2-3-3"): "Glucose",
    ("researchnet", "2-4-1"): "PZA",
    ("researchnet", "2-4-2"): "INH",
    ("researchnet", "2-4-3"): "PAS",
    ("researchnet", "2-5-1"): "Fusion - Germane",
    ("researchnet", "2-5-2"): "Fusion - Silane",
    ("researchnet", "2-5-3"): "Fermentation",
    ("researchnet", "2-6-1"): "Hydrazine",
    ("researchnet", "2-6-2"): "Organometallics",
    ("researchnet", "2-6-3"): "Nonsense!",
    ("researchnet", "2-7-1"): "Iron and Ozone",
    ("researchnet", "2-7-2"): "Normalization",
    ("researchnet", "2-7-3"): "Decomposition",
    ("researchnet", "2-8-1"): "Phenol",
    ("researchnet", "2-8-2"): "Uracil",
    ("researchnet", "2-8-3"): "Pyridine",
    ("researchnet", "2-9-1"): "Phosgene",
    ("researchnet", "2-9-2"): "Ignoble",
    ("researchnet", "2-9-3"): "Alchemy",
    ("researchnet", "2-10-1"): "Bosch-Meiser",
    ("researchnet", "2-10-2"): "Beckmann Rearrangement",
    ("researchnet", "2-10-3"): "Stock-Pohland",
    ("researchnet", "2-11-1"): "Swapite",
    ("researchnet", "2-11-2"): "Hardening",
    ("researchnet", "2-11-3"): "Keying In",
    ("researchnet", "2-12-1"): "Ethane",
    ("researchnet", "2-12-2"): "Cyclobutane",
    ("researchnet", "2-12-3"): "Styrene",

    ("researchnet", "3-1-1"): "Thinner Line",
    ("researchnet", "3-1-2"): "Decomposition of Ethanolamine",
    ("researchnet", "3-1-3"): "Anesthetics",
    ("researchnet", "3-2-1"): "Fertigprodukt",
    ("researchnet", "3-2-2"): "Novel Semiconductor",
    ("researchnet", "3-2-3"): "Passivation",
    ("researchnet", "3-3-1"): "Life: Prep Work",
    ("researchnet", "3-3-2"): "Life: Cytosine",
    ("researchnet", "3-3-3"): "Life: Thymine",
    ("researchnet", "3-4-1"): "Cyanamide",
    ("researchnet", "3-4-2"): "Acetic Acid",
    ("researchnet", "3-4-3"): "Combustion Engine",
    ("researchnet", "3-5-1"): "Smelting Iron",
    ("researchnet", "3-5-2"): "Neodymium Magnet",
    ("researchnet", "3-5-3"): "Carbide Swap",
    ("researchnet", "3-6-1"): "Fuel Production",
    ("researchnet", "3-6-2"): "Siliconheart Piece",
    ("researchnet", "3-6-3"): "Raygun Mechanism",
    ("researchnet", "3-7-1"): "Sulfuric Acid",
    ("researchnet", "3-7-2"): "Fuming Nitric Acid",
    ("researchnet", "3-7-3"): "Rocket Fuel",
    ("researchnet", "3-8-1"): "Hydroxides",
    ("researchnet", "3-8-2"): "Nobility",
    ("researchnet", "3-8-3"): "Sortite",
    ("researchnet", "3-9-1"): "Radiation Treatment",
    ("researchnet", "3-9-2"): "Boron Compounds",
    ("researchnet", "3-9-3"): "Photovoltaic Cells",
    ("researchnet", "3-10-1"): "Elementary",
    ("researchnet", "3-10-2"): "Mixed Acids",
    ("researchnet", "3-10-3"): "Squaric Acid",
    ("researchnet", "3-11-1"): "Misproportioned",
    ("researchnet", "3-11-2"): "Narkotikum",
    ("researchnet", "3-11-3"): "Vereinheitlichung",
    ("researchnet", "3-12-1"): "Haber-Bosch",
    ("researchnet", "3-12-2"): "Mustard Oil",
    ("researchnet", "3-12-3"): "Nano Electric Motor",

    ("researchnet", "4-1-1"): "Count",
    ("researchnet", "4-1-2"): "Sharing is Caring",
    ("researchnet", "4-1-3"): "Reassembly",
    ("researchnet", "4-2-1"): "Cyanogen",
    ("researchnet", "4-2-2"): "Chloromethylsilane",
    ("researchnet", "4-2-3"): "Glyceraldehyde",
    ("researchnet", "4-3-1"): "Ethandiamin",
    ("researchnet", "4-3-2"): "Radikal",
    ("researchnet", "4-3-3"): "Kreisalkanol",
    ("researchnet", "4-4-1"): "Inorganic Pigments",
    ("researchnet", "4-4-2"): "Miller-Urey",
    ("researchnet", "4-4-3"): "Getting Pumped",
    ("researchnet", "4-5-1"): "Lewisite",
    ("researchnet", "4-5-2"): "Novichok",
    ("researchnet", "4-5-3"): "Ribulose",
    ("researchnet", "4-6-1"): "Knockout Drops",
    ("researchnet", "4-6-2"): "Strong Acids",
    ("researchnet", "4-6-3"): "Vitamin B3",
    ("researchnet", "4-7-1"): "1,2,3-Triphenol",
    ("researchnet", "4-7-2"): "1,3-Dimetoxibencene",
    ("researchnet", "4-7-3"): "Think in Spirals",
    ("researchnet", "4-8-1"): "Yellowcake",
    ("researchnet", "4-8-2"): "Thiourea",
    ("researchnet", "4-8-3"): "Downgrade",
    ("researchnet", "4-9-1"): "Wood Alcohol",
    ("researchnet", "4-9-2"): "Allyl Alcohol",
    ("researchnet", "4-9-3"): "Propargyl Alcohol",
    ("researchnet", "4-10-1"): "Condensation",
    ("researchnet", "4-10-2"): "Silane",
    ("researchnet", "4-10-3"): "Phosphine",
    ("researchnet", "4-11-1"): "Nuclear Medicine",
    ("researchnet", "4-11-2"): "Oxygen Supply",
    ("researchnet", "4-11-3"): "Red Cross",
    ("researchnet", "4-12-1"): "Fluoromethanes",
    ("researchnet", "4-12-2"): "Exercise",
    ("researchnet", "4-12-3"): "Nanoboxes",

    ("researchnet", "5-1-1"): "PAX Challenge 1",
    ("researchnet", "5-1-2"): "PAX Challenge 2",
    ("researchnet", "5-1-3"): "PAX Challenge 3",
    ("researchnet", "5-2-1"): "Fill in the Blank",
    ("researchnet", "5-2-2"): "Break-up",
    ("researchnet", "5-2-3"): "Average Out",
    ("researchnet", "5-3-1"): "Fake Out",
    ("researchnet", "5-3-2"): "Breakdown",
    ("researchnet", "5-3-3"): "Master of Disguise",
    ("researchnet", "5-4-1"): "Thermoplastic",
    ("researchnet", "5-4-2"): "Contaminated",
    ("researchnet", "5-4-3"): "Running Low",
    ("researchnet", "5-5-1"): "Not a Planet",
    ("researchnet", "5-5-2"): "Back to Basics",
    ("researchnet", "5-5-3"): "Not Helping",
    ("researchnet", "5-6-1"): "Two-fer",
    ("researchnet", "5-6-2"): "Oxygen Synthesis",
    ("researchnet", "5-6-3"): "Stupor",
    ("researchnet", "5-7-1"): "Oxygen Synthesis for Kids",
    ("researchnet", "5-7-2"): "+1",
    ("researchnet", "5-7-3"): "Nuclear Sorting",
    ("researchnet", "5-8-1"): "Fun with Oxides",
    ("researchnet", "5-8-2"): "Overflow",
    ("researchnet", "5-8-3"): "Conversion",
    ("researchnet", "5-9-1"): "Benzene Machine",
    ("researchnet", "5-9-2"): "Speedster",
    ("researchnet", "5-9-3"): "Carbon Splatter",
    ("researchnet", "5-10-1"): "Eth",
    ("researchnet", "5-10-2"): "Large Scale",
    ("researchnet", "5-10-3"): "Revenge",
    ("researchnet", "5-11-1"): "Excess",
    ("researchnet", "5-11-2"): "Carbon Compounds",
    ("researchnet", "5-11-3"): "Magnesium Bicarbonate",
    ("researchnet", "5-12-1"): "Impostor",
    ("researchnet", "5-12-2"): "Master Plan",
    ("researchnet", "5-12-3"): "Rags to Riches",

    ("researchnet", "6-1-1"): "Plutonium Separator",
    ("researchnet", "6-1-2"): "You're doing it wrong",
    ("researchnet", "6-1-3"): "Synthetic Elerium",
    ("researchnet", "6-2-1"): "Deadly Soft Drinks",
    ("researchnet", "6-2-2"): "Deadly Fluorinate...",
    ("researchnet", "6-2-3"): "Deadly Microwaves",
    ("researchnet", "6-3-1"): "Carbon Snakes",
    ("researchnet", "6-3-2"): "Catalyst",
    ("researchnet", "6-3-3"): "Catalyst II",
    ("researchnet", "6-4-1"): "Unbonding with n...",
    ("researchnet", "6-4-2"): "Breeder Reactor",
    ("researchnet", "6-4-3"): "Nightmare Factory",

    ("researchnet", "7-1-1"): "Fructose Factory",
    ("researchnet", "7-1-2"): "Misfortune Modifier",
    ("researchnet", "7-1-3"): "Particle Accelerator",
    ("researchnet", "7-2-1"): "Sun Simulator",
    ("researchnet", "7-2-2"): "100",
    ("researchnet", "7-2-3"): "Hypothetical Synthesis",
    ("researchnet", "7-3-1"): "Halogen Sorting",
    ("researchnet", "7-3-2"): "Metallica",
    ("researchnet", "7-3-3"): "Homogenizer",
    ("researchnet", "7-4-1"): "Dessication Station",
    ("researchnet", "7-4-2"): "Vinegar Distillation",
    ("researchnet", "7-4-3"): "A Glass of Water",
    ("researchnet", "7-5-1"): "Pertetroxide Synthesis",
    ("researchnet", "7-5-2"): "Fantastic Metals",
    ("researchnet", "7-5-3"): "Reppe Chemistry",
    ("researchnet", "7-6-1"): "Better Than Graphene",
    ("researchnet", "7-6-2"): "Magnets",
    ("researchnet", "7-6-3"): "Precious Oxygen",

    ("researchnet", "8-1-1"): "Dewer Benzene",
    ("researchnet", "8-1-2"): "Natural Chemo",
    ("researchnet", "8-1-3"): "The Chem in Spac...",
    ("researchnet", "8-2-1"): "Airborne Aldehyde",
    ("researchnet", "8-2-2"): "Natural Gas",
    ("researchnet", "8-2-3"): "Symmetry",
    ("researchnet", "8-3-1"): "Fenton Industries...",
    ("researchnet", "8-3-2"): "Oxygen Candle",
    ("researchnet", "8-3-3"): "Lies",
    ("researchnet", "8-4-1"): "Liquid Glass",
    ("researchnet", "8-4-2"): "PVC V",
    ("researchnet", "8-4-3"): "Memories",
    ("researchnet", "8-5-1"): "Tumbler",
    ("researchnet", "8-5-2"): "Molecular Key Car...",
    ("researchnet", "8-5-3"): "Sensitive Explosiv...",
    ("researchnet", "8-6-1"): "Waste Gas",
    ("researchnet", "8-6-2"): "Ethane Scrubbing",
    ("researchnet", "8-6-3"): "Melanophlogite Cla...",
    ("researchnet", "8-7-1"): "Largest Prime",
    ("researchnet", "8-7-2"): "Three",
    ("researchnet", "8-7-3"): "Θne",
    ("researchnet", "8-8-1"): "A Small Push",
    ("researchnet", "8-8-2"): "Pushed Together",
    ("researchnet", "8-8-3"): "Repair Tungsten",
    ("researchnet", "8-9-1"): "Shared Space I",
    ("researchnet", "8-9-2"): "Shared Space II",
    ("researchnet", "8-9-3"): "Taking Turns",
    ("researchnet", "8-10-1"): "How Ionic",
    ("researchnet", "8-10-2"): "Two by Two",
    ("researchnet", "8-10-3"): "The Gold Standard",
    ("researchnet", "8-11-1"): "2 of Hearts",
    ("researchnet", "8-11-2"): "Miracle Cure",
    ("researchnet", "8-11-3"): "Oxygen Snake",
    ("researchnet", "8-12-1"): "That's a Relief",
    ("researchnet", "8-12-2"): "Headaches",
    ("researchnet", "8-12-3"): "Under the Counter",
    ("researchnet", "8-13-1"): "A New Beginning",
    ("researchnet", "8-13-2"): "Discombobulate",
    ("researchnet", "8-13-3"): "Magnum Opus",
    ("researchnet", "8-14-1"): "Organic Fusion Ch...",
    ("researchnet", "8-14-2"): "The Soul of Iron",
    ("researchnet", "8-14-3"): "Serbalcide",
    ("researchnet", "8-15-1"): "Precious Tears",
    ("researchnet", "8-15-2"): "Desperate Measur...",
    ("researchnet", "8-15-3"): "Hydrocarbon Stitch",

}
