save2id = {

    "research-example-1": ("main", "1-1"),
    "research-tutorial-1": ("main", "1-2"),
    "research-tutorial-1point5": ("main", "1-3"),
    "research-example-2": ("main", "1-4"),
    "research-tutorial-2": ("main", "1-5"),
    "research-tutorial-3": ("main", "1-6"),

    "research-tutorial-4": ("main", "2-1"),
    "research-tutorial-5": ("main", "2-2"),
    "research-tutorial-6": ("main", "2-3"),
    "production-tutorial-1": ("main", "2-4"),
    "production-tutorial-2": ("main", "2-5"),
    "production-tutorial-3": ("main", "2-6"),

    "bonding-2": ("main", "3-1"),
    "bonding-3": ("main", "3-2"),
    "bonding-4": ("main", "3-3"),
    "bonding-6": ("main", "3-4"),
    "bonding-7": ("main", "3-5"),
    "bonding-boss": ('main', '3-6'),
    "bonding-5": ("main", "3-C"),

    "sensing-1": ("main", "4-1"),
    "sensing-2": ("main", "4-2"),
    "sensing-3": ("main", "4-3"),
    "sensing-4": ("main", "4-4"),
    "sensing-5": ("main", "4-5"),
    "sensing-boss": ('main', '4-6'),
    "sensing-6": ("main", "4-C"),
    
    "fusion-1": ("main", "5-1"),
    "fusion-2": ("main", "5-2"),
    "fusion-3": ("main", "5-3"),
    "fusion-5": ("main", "5-4"),
    "fusion-boss": ('main', '5-5'),
    "fusion-6": ("main", "5-C"),

    "mining-2": ("main", "6-1"),
    "mining-3": ("main", "6-2"),
    "mining-7": ("main", "6-3"),
    "mining-1": ("main", "6-4"),
    "mining-5": ("main", "6-6"),
    "mining-4": ("main", "6-7"),
    "mining-boss": ('main', '6-5'),
    "mining-6": ("main", "6-C"),

    "research-1": ("main", "7-1"),
    "research-3": ("main", "7-2"),
    "research-6": ("main", "7-3"),
    "research-5": ("main", "7-4"),
    "research-2": ("main", "7-5"),
    "research-boss": ('main', '7-6'),

    "organic-1": ("main", "8-1"),
    "organic-2": ("main", "8-2"),
    "organic-3": ("main", "8-3"),
    "organic-5": ("main", "8-5a"),
    "organic-6": ("main", "8-5b"),
    "organic-boss": ('main', '8-4'),

    "warp-boss": ('main', '9-1'),


    "tf2-1": ("tf2", "TF2-1"),
    "tf2-2": ("tf2", "TF2-2"),
    "tf2-3": ("tf2", "TF2-3"),


    "quantum-1": ("63corvi", "1"),
    "quantum-2": ("63corvi", "2"),
    "quantum-4": ("63corvi", "3"),
    "quantum-3": ("63corvi", "4"),
    "quantum-5": ("63corvi", "5"),
    "quantum-6": ("63corvi", "6"),
    "quantum-boss": ('63corvi', '7'),


    "published-1-1": ("researchnet", "1-1-1"),
    "published-1-2": ("researchnet", "1-1-2"),
    "published-1-3": ("researchnet", "1-1-3"),
    "published-2-1": ("researchnet", "1-2-1"),
    "published-2-2": ("researchnet", "1-2-2"),
    "published-2-3": ("researchnet", "1-2-3"),
    "published-3-1": ("researchnet", "1-3-1"),
    "published-3-2": ("researchnet", "1-3-2"),
    "published-3-3": ("researchnet", "1-3-3"),
    "published-4-1": ("researchnet", "1-4-1"),
    "published-4-2": ("researchnet", "1-4-2"),
    "published-4-3": ("researchnet", "1-4-3"),
    "published-5-1": ("researchnet", "1-5-1"),
    "published-5-2": ("researchnet", "1-5-2"),
    "published-5-3": ("researchnet", "1-5-3"),
    "published-6-1": ("researchnet", "1-6-1"),
    "published-6-2": ("researchnet", "1-6-2"),
    "published-6-3": ("researchnet", "1-6-3"),
    "published-7-1": ("researchnet", "1-7-1"),
    "published-7-2": ("researchnet", "1-7-2"),
    "published-7-3": ("researchnet", "1-7-3"),
    "published-8-1": ("researchnet", "1-8-1"),
    "published-8-2": ("researchnet", "1-8-2"),
    "published-8-3": ("researchnet", "1-8-3"),
    "published-9-1": ("researchnet", "1-9-1"),
    "published-9-2": ("researchnet", "1-9-2"),
    "published-9-3": ("researchnet", "1-9-3"),
    "published-10-1": ("researchnet", "1-10-1"),
    "published-10-2": ("researchnet", "1-10-2"),
    "published-10-3": ("researchnet", "1-10-3"),
    "published-11-1": ("researchnet", "1-11-1"),
    "published-11-2": ("researchnet", "1-11-2"),
    "published-11-3b": ("researchnet", "1-11-3"),
    "published-12-1": ("researchnet", "1-12-1"),
    "published-12-2": ("researchnet", "1-12-2"),
    "published-12-3": ("researchnet", "1-12-3"),

    "published-13-1": ("researchnet", "2-1-1"),
    "published-13-2": ("researchnet", "2-1-2"),
    "published-13-3": ("researchnet", "2-1-3"),
    "published-14-1": ("researchnet", "2-2-1"),
    "published-14-2": ("researchnet", "2-2-2"),
    "published-14-3": ("researchnet", "2-2-3"),
    "published-15-1": ("researchnet", "2-3-1"),
    "published-15-2": ("researchnet", "2-3-2"),
    "published-15-3": ("researchnet", "2-3-3"),
    "published-16-1": ("researchnet", "2-4-1"),
    "published-16-2": ("researchnet", "2-4-2"),
    "published-16-3": ("researchnet", "2-4-3"),
    "published-17-1": ("researchnet", "2-5-1"),
    "published-17-2": ("researchnet", "2-5-2"),
    "published-17-3": ("researchnet", "2-5-3"),
    "published-18-1": ("researchnet", "2-6-1"),
    "published-18-2": ("researchnet", "2-6-2"),
    "published-18-3": ("researchnet", "2-6-3"),
    "published-19-1": ("researchnet", "2-7-1"),
    "published-19-2": ("researchnet", "2-7-2"),
    "published-19-3": ("researchnet", "2-7-3"),
    "published-20-1": ("researchnet", "2-8-1"),
    "published-20-2": ("researchnet", "2-8-2"),
    "published-20-3": ("researchnet", "2-8-3"),
    "published-21-1": ("researchnet", "2-9-1"),
    "published-21-2": ("researchnet", "2-9-2"),
    "published-21-3": ("researchnet", "2-9-3"),
    "published-22-1": ("researchnet", "2-10-1"),
    "published-22-2": ("researchnet", "2-10-2"),
    "published-22-3": ("researchnet", "2-10-3"),
    "published-23-1": ("researchnet", "2-11-1"),
    "published-23-2": ("researchnet", "2-11-2"),
    "published-23-3": ("researchnet", "2-11-3"),
    "published-24-1": ("researchnet", "2-12-1"),
    "published-24-2": ("researchnet", "2-12-2"),
    "published-24-3": ("researchnet", "2-12-3"),

    "published-25-1": ("researchnet", "3-1-1"),
    "published-25-2": ("researchnet", "3-1-2"),
    "published-25-3": ("researchnet", "3-1-3"),
    "published-26-1": ("researchnet", "3-2-1"),
    "published-26-2": ("researchnet", "3-2-2"),
    "published-26-3": ("researchnet", "3-2-3"),
    "published-27-1": ("researchnet", "3-3-1"),
    "published-27-2": ("researchnet", "3-3-2"),
    "published-27-3": ("researchnet", "3-3-3"),
    "published-28-1": ("researchnet", "3-4-1"),
    "published-28-2": ("researchnet", "3-4-2"),
    "published-28-3": ("researchnet", "3-4-3"),
    "published-29-1": ("researchnet", "3-5-1"),
    "published-29-2": ("researchnet", "3-5-2"),
    "published-29-3": ("researchnet", "3-5-3"),
    "published-30-1": ("researchnet", "3-6-1"),
    "published-30-2": ("researchnet", "3-6-2"),
    "published-30-3": ("researchnet", "3-6-3"),
    "published-31-1": ("researchnet", "3-7-1"),
    "published-31-2": ("researchnet", "3-7-2"),
    "published-31-3": ("researchnet", "3-7-3"),
    "published-32-1": ("researchnet", "3-8-1"),
    "published-32-2": ("researchnet", "3-8-2"),
    "published-32-3": ("researchnet", "3-8-3"),
    "published-33-1": ("researchnet", "3-9-1"),
    "published-33-2": ("researchnet", "3-9-2"),
    "published-33-3": ("researchnet", "3-9-3"),
    "published-34-1": ("researchnet", "3-10-1"),
    "published-34-2": ("researchnet", "3-10-2"),
    "published-34-3": ("researchnet", "3-10-3"),
    "published-35-1": ("researchnet", "3-11-1"),
    "published-35-2": ("researchnet", "3-11-2"),
    "published-35-3": ("researchnet", "3-11-3"),
    "published-36-1": ("researchnet", "3-12-1"),
    "published-36-2": ("researchnet", "3-12-2"),
    "published-36-3": ("researchnet", "3-12-3"),

    "published-37-1": ("researchnet", "4-1-1"),
    "published-37-2": ("researchnet", "4-1-2"),
    "published-37-3": ("researchnet", "4-1-3"),
    "published-38-1": ("researchnet", "4-2-1"),
    "published-38-2": ("researchnet", "4-2-2"),
    "published-38-3": ("researchnet", "4-2-3"),
    "published-39-1": ("researchnet", "4-3-1"),
    "published-39-2": ("researchnet", "4-3-2"),
    "published-39-3": ("researchnet", "4-3-3"),
    "published-40-1": ("researchnet", "4-4-1"),
    "published-40-2": ("researchnet", "4-4-2"),
    "published-40-3": ("researchnet", "4-4-3"),
    "published-41-1": ("researchnet", "4-5-1"),
    "published-41-2": ("researchnet", "4-5-2"),
    "published-41-3": ("researchnet", "4-5-3"),
    "published-42-1": ("researchnet", "4-6-1"),
    "published-42-2": ("researchnet", "4-6-2"),
    "published-42-3": ("researchnet", "4-6-3"),
    "published-43-1": ("researchnet", "4-7-1"),
    "published-43-2": ("researchnet", "4-7-2"),
    "published-43-3": ("researchnet", "4-7-3"),
    "published-44-1": ("researchnet", "4-8-1"),
    "published-44-2": ("researchnet", "4-8-2"),
    "published-44-3": ("researchnet", "4-8-3"),
    "published-45-1": ("researchnet", "4-9-1"),
    "published-45-2": ("researchnet", "4-9-2"),
    "published-45-3": ("researchnet", "4-9-3"),
    "published-46-1": ("researchnet", "4-10-1"),
    "published-46-2": ("researchnet", "4-10-2"),
    "published-46-3": ("researchnet", "4-10-3"),
    "published-47-1": ("researchnet", "4-11-1"),
    "published-47-2": ("researchnet", "4-11-2"),
    "published-47-3": ("researchnet", "4-11-3"),
    "published-48-1": ("researchnet", "4-12-1"),
    "published-48-2": ("researchnet", "4-12-2"),
    "published-48-3": ("researchnet", "4-12-3"),

    "published-49-1": ("researchnet", "5-1-1"),
    "published-49-2": ("researchnet", "5-1-2"),
    "published-49-3": ("researchnet", "5-1-3"),
    "published-50-1": ("researchnet", "5-2-1"),
    "published-50-2": ("researchnet", "5-2-2"),
    "published-50-3": ("researchnet", "5-2-3"),
    "published-51-1": ("researchnet", "5-3-1"),
    "published-51-2": ("researchnet", "5-3-2"),
    "published-51-3": ("researchnet", "5-3-3"),
    "published-52-1": ("researchnet", "5-4-1"),
    "published-52-2": ("researchnet", "5-4-2"),
    "published-52-3": ("researchnet", "5-4-3"),
    "published-53-1": ("researchnet", "5-5-1"),
    "published-53-2": ("researchnet", "5-5-2"),
    "published-53-3": ("researchnet", "5-5-3"),
    "published-54-1": ("researchnet", "5-6-1"),
    "published-54-2": ("researchnet", "5-6-2"),
    "published-54-3": ("researchnet", "5-6-3"),
    "published-55-1": ("researchnet", "5-7-1"),
    "published-55-2": ("researchnet", "5-7-2"),
    "published-55-3": ("researchnet", "5-7-3"),
    "published-56-1": ("researchnet", "5-8-1"),
    "published-56-2": ("researchnet", "5-8-2"),
    "published-56-3": ("researchnet", "5-8-3"),
    "published-57-1": ("researchnet", "5-9-1"),
    "published-57-2": ("researchnet", "5-9-2"),
    "published-57-3": ("researchnet", "5-9-3"),
    "published-58-1": ("researchnet", "5-10-1"),
    "published-58-2": ("researchnet", "5-10-2"),
    "published-58-3": ("researchnet", "5-10-3"),
    "published-59-1": ("researchnet", "5-11-1"),
    "published-59-2": ("researchnet", "5-11-2"),
    "published-59-3": ("researchnet", "5-11-3"),
    "published-60-1": ("researchnet", "5-12-1"),
    "published-60-2": ("researchnet", "5-12-2"),
    "published-60-3": ("researchnet", "5-12-3"),

    "published-61-1": ("researchnet", "6-1-1"),
    "published-61-2": ("researchnet", "6-1-2"),
    "published-61-3": ("researchnet", "6-1-3"),
    "published-62-1": ("researchnet", "6-2-1"),
    "published-62-2": ("researchnet", "6-2-2"),
    "published-62-3": ("researchnet", "6-2-3"),
    "published-63-1": ("researchnet", "6-3-1"),
    "published-63-2": ("researchnet", "6-3-2"),
    "published-63-3": ("researchnet", "6-3-3"),
    "published-64-1": ("researchnet", "6-4-1"),
    "published-64-2": ("researchnet", "6-4-2"),
    "published-64-3": ("researchnet", "6-4-3"),

    "published-71-1": ("researchnet", "7-1-1"),
    "published-71-2": ("researchnet", "7-1-2"),
    "published-71-3": ("researchnet", "7-1-3"),
    "published-72-1": ("researchnet", "7-2-1"),
    "published-72-2": ("researchnet", "7-2-2"),
    "published-72-3": ("researchnet", "7-2-3"),
    "published-73-1": ("researchnet", "7-3-1"),
    "published-73-2": ("researchnet", "7-3-2"),
    "published-73-3": ("researchnet", "7-3-3"),
    "published-74-1": ("researchnet", "7-4-1"),
    "published-74-2": ("researchnet", "7-4-2"),
    "published-74-3": ("researchnet", "7-4-3"),
    "published-75-1": ("researchnet", "7-5-1"),
    "published-75-2": ("researchnet", "7-5-2"),
    "published-75-3": ("researchnet", "7-5-3"),
    "published-76-1": ("researchnet", "7-6-1"),
    "published-76-2": ("researchnet", "7-6-2"),
    "published-76-3": ("researchnet", "7-6-3"),

    "published-77-1": ("researchnet", "8-1-1"),
    "published-77-2": ("researchnet", "8-1-2"),
    "published-77-3": ("researchnet", "8-1-3"),
    "published-78-1": ("researchnet", "8-2-1"),
    "published-78-2": ("researchnet", "8-2-2"),
    "published-78-3": ("researchnet", "8-2-3"),
    "published-79-1": ("researchnet", "8-3-1"),
    "published-79-2": ("researchnet", "8-3-2"),
    "published-79-3": ("researchnet", "8-3-3"),
    "published-80-1": ("researchnet", "8-4-1"),
    "published-80-2": ("researchnet", "8-4-2"),
    "published-80-3": ("researchnet", "8-4-3"),
    "published-81-1": ("researchnet", "8-5-1"),
    "published-81-2": ("researchnet", "8-5-2"),
    "published-81-3": ("researchnet", "8-5-3"),
    "published-82-1": ("researchnet", "8-6-1"),
    "published-82-2": ("researchnet", "8-6-2"),
    "published-82-3": ("researchnet", "8-6-3"),
    "published-83-1": ("researchnet", "8-7-1"),
    "published-83-2": ("researchnet", "8-7-2"),
    "published-83-3": ("researchnet", "8-7-3"),
    "published-84-1": ("researchnet", "8-8-1"),
    "published-84-2": ("researchnet", "8-8-2"),
    "published-84-3": ("researchnet", "8-8-3"),
    "published-85-1": ("researchnet", "8-9-1"),
    "published-85-2": ("researchnet", "8-9-2"),
    "published-85-3": ("researchnet", "8-9-3"),
    "published-86-1": ("researchnet", "8-10-1"),
    "published-86-2": ("researchnet", "8-10-2"),
    "published-86-3": ("researchnet", "8-10-3"),
    "published-87-1": ("researchnet", "8-11-1"),
    "published-87-2": ("researchnet", "8-11-2"),
    "published-87-3": ("researchnet", "8-11-3"),
    "published-88-1": ("researchnet", "8-12-1"),
    "published-88-2": ("researchnet", "8-12-2"),
    "published-88-3": ("researchnet", "8-12-3"),
    "published-89-1": ("researchnet", "8-13-1"),
    "published-89-2": ("researchnet", "8-13-2"),
    "published-89-3": ("researchnet", "8-13-3"),
    "published-90-1": ("researchnet", "8-14-1"),
    "published-90-2": ("researchnet", "8-14-2"),
    "published-90-3": ("researchnet", "8-14-3"),
    "published-91-1": ("researchnet", "8-15-1"),
    "published-91-2": ("researchnet", "8-15-2"),
    "published-91-3": ("researchnet", "8-15-3"),
}

id2level = {

    ("main", "1-1"): {'name': "Of Pancakes and Spaceships", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "1-2"): {'name': "Slightly Different", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "1-3"): {'name': "Crossover", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "1-4"): {'name': "An Introduction to Bonding", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "1-5"): {'name': "A Brief History of SpaceChem", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "1-6"): {'name': "Removing Bonds", 'isResearch': 1, 'isDeterministic': 1},

    ("main", "2-1"): {'name': "Double Bonds", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "2-2"): {'name': "Best Left Unanswered", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "2-3"): {'name': "Multiple Outputs", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "2-4"): {'name': "An Introduction to Pipelines", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "2-5"): {'name': "There's Something in the Fishcake", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "2-6"): {'name': "Sleepless on Sernimir IV", 'isResearch': 1, 'isDeterministic': 1},

    ("main", "3-1"): {'name': "Every Day is the First Day", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "3-2"): {'name': "It Takes Three", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "3-3"): {'name': "Split Before Bonding", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "3-4"): {'name': "Settling into the Routine", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "3-5"): {'name': "Nothing Works", 'isResearch': 0, 'isDeterministic': 1},
    ('main', '3-6'): {'name': "A Most Unfortunate Malfunction", 'isResearch': 0, 'isDeterministic': 1},
    ("main", "3-C"): {'name': "Challenge: In-Place Swap", 'isResearch': 0, 'isDeterministic': 1},

    ("main", "4-1"): {'name': "An Introduction to Sensing", 'isResearch': 1, 'isDeterministic': 0},
    ("main", "4-2"): {'name': "Prelude to a Migraine", 'isResearch': 1, 'isDeterministic': 0},
    ("main", "4-3"): {'name': "Random Oxides", 'isResearch': 1, 'isDeterministic': 0},
    ("main", "4-4"): {'name': "No Ordinary Headache", 'isResearch': 0, 'isDeterministic': 0},
    ("main", "4-5"): {'name': "No Thanks Necessary", 'isResearch': 0, 'isDeterministic': 0},
    ('main', '4-6'): {'name': "No Need for Introductions", 'isResearch': 0, 'isDeterministic': 0},
    ("main", "4-C"): {'name': "Challenge: Going Green", 'isResearch': 0, 'isDeterministic': 0},

    ("main", "5-1"): {'name': "Ice to Meet You", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "5-2"): {'name': "Under the Ice", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "5-3"): {'name': "Unknown Sender", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "5-4"): {'name': "Falling", 'isResearch': 0, 'isDeterministic': 1},
    ('main', '5-5'): {'name': "Exploding Head Syndrome", 'isResearch': 0, 'isDeterministic': 1},
    ("main", "5-C"): {'name': "Challenge: Applied Fusion", 'isResearch': 0, 'isDeterministic': 1},

    ("main", "6-1"): {'name': "Like a Boss", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "6-2"): {'name': "Sacré Bleu!", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "6-3"): {'name': "The Plot Thickens", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "6-4"): {'name': "Danger Zone", 'isResearch': 1, 'isDeterministic': 0},
    ("main", "6-6"): {'name': "Molecular Foundry", 'isResearch': 0, 'isDeterministic': 0},
    ("main", "6-7"): {'name': "Gas Works Park", 'isResearch': 0, 'isDeterministic': 0},
    ('main', '6-5'): {'name': "More than Machine", 'isResearch': 0, 'isDeterministic': 0},
    ("main", "6-C"): {'name': "Challenge: KOHCTPYKTOP", 'isResearch': 0, 'isDeterministic': 1},

    ("main", "7-1"): {'name': "The Blue Danube", 'isResearch': 1, 'isDeterministic': 0},
    ("main", "7-2"): {'name': "No Stomach for Lunch", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "7-3"): {'name': "No Employment Record Found", 'isResearch': 1, 'isDeterministic': 0},
    ("main", "7-4"): {'name': "Right All Along", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "7-5"): {'name': "Accidents Happen", 'isResearch': 1, 'isDeterministic': 0},
    ('main', '7-6'): {'name': "Don't Fear the Reaper", 'isResearch': 0, 'isDeterministic': 1},

    ("main", "8-1"): {'name': "Special Assignment", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "8-2"): {'name': "Suspicious Behavior", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "8-3"): {'name': "I Told You So", 'isResearch': 1, 'isDeterministic': 1},
    ("main", "8-5a"): {'name': "Ω-Pseudoethyne", 'isResearch': 1, 'isDeterministic': 0},
    ("main", "8-5b"): {'name': "Σ-Ethylene", 'isResearch': 1, 'isDeterministic': 1},
    ('main', '8-4'): {'name': "Freedom of Choice", 'isResearch': 0, 'isDeterministic': 1},

    ('main', '9-1'): {'name': "End of the Line", 'isResearch': 0, 'isDeterministic': 1},


    ("tf2", "TF2-1"): {'name': "Moustachium 602", 'isResearch': 1, 'isDeterministic': 1},
    ("tf2", "TF2-2"): {'name': "Moustachium 604", 'isResearch': 1, 'isDeterministic': 1},
    ("tf2", "TF2-3"): {'name': "Moustachium 608", 'isResearch': 1, 'isDeterministic': 1},


    ("63corvi", "1"): {'name': "QT-1", 'isResearch': 1, 'isDeterministic': 1},
    ("63corvi", "2"): {'name': "QT-2", 'isResearch': 1, 'isDeterministic': 1},
    ("63corvi", "3"): {'name': "Teleporters", 'isResearch': 0, 'isDeterministic': 1},
    ("63corvi", "4"): {'name': "QT-3", 'isResearch': 1, 'isDeterministic': 1},
    ("63corvi", "5"): {'name': "QT-4", 'isResearch': 1, 'isDeterministic': 1},
    ("63corvi", "6"): {'name': "Precursor Compounds", 'isResearch': 0, 'isDeterministic': 0},
    ('63corvi', '7'): {'name': "Collapsar", 'isResearch': 0, 'isDeterministic': 1},

    
    ("researchnet", "1-1-1"): {'name': "Tunnels I", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-1-2"): {'name': "Tunnels II", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-1-3"): {'name': "Tunnels III", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-2-1"): {'name': "Fission I", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-2-2"): {'name': "Fission II", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-2-3"): {'name': "Fission III", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-3-1"): {'name': "Chloroform", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-3-2"): {'name': "Cycloaddition", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-3-3"): {'name': "KOHCTPYKTOP++", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "1-4-1"): {'name': "Quantum Decomposition", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-4-2"): {'name': "Propane Accessories", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-4-3"): {'name': "Benzoic Acid", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-5-1"): {'name': "Electrophilic Addition", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-5-2"): {'name': "Diethyl Ether", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-5-3"): {'name': "2-Hexene", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-6-1"): {'name': "Mazeite'", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-6-2"): {'name': "Silica", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-6-3"): {'name': "Galvanization", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-7-1"): {'name': "Industrial Methanol", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-7-2"): {'name': "Glyoxylic Acid", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-7-3"): {'name': "Bioplastic", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-8-1"): {'name': "Chlorination", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-8-2"): {'name': "Sulfuric Acid", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-8-3"): {'name': "Bad Times", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-9-1"): {'name': "Friedel-Crafts", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-9-2"): {'name': "Wöhler Synthesis", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-9-3"): {'name': "Diels-Alder", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-10-1"): {'name': "Bad Times, Part II", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-10-2"): {'name': "Freon", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "1-10-3"): {'name': "Benzene Derivatives", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "1-11-1"): {'name': "Portland Cement", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-11-2"): {'name': "Solder Coarsening", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-11-3"): {'name': "Graphene", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-12-1"): {'name': "The Big Cleanup", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "1-12-2"): {'name': "Going Green Part II", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "1-12-3"): {'name': "Waste Treatment", 'isResearch': 1, 'isDeterministic': 0},

    ("researchnet", "2-1-1"): {'name': "Pyridine", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-1-2"): {'name': "Breakdown", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-1-3"): {'name': "Vitamin B3", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-2-1"): {'name': "PVC", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-2-2"): {'name': "PVA", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-2-3"): {'name': "Naphthalene", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-3-1"): {'name': "Anthraquinone", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-3-2"): {'name': "Soap", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-3-3"): {'name': "Glucose", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-4-1"): {'name': "PZA", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-4-2"): {'name': "INH", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-4-3"): {'name': "PAS", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-5-1"): {'name': "Fusion - Germane", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-5-2"): {'name': "Fusion - Silane", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-5-3"): {'name': "Fermentation", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-6-1"): {'name': "Hydrazine", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-6-2"): {'name': "Organometallics", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-6-3"): {'name': "Nonsense!", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "2-7-1"): {'name': "Iron and Ozone", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-7-2"): {'name': "Normalization", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "2-7-3"): {'name': "Decomposition", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-8-1"): {'name': "Phenol", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-8-2"): {'name': "Uracil", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-8-3"): {'name': "Pyridine", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "2-9-1"): {'name': "Phosgene", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-9-2"): {'name': "Ignoble", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-9-3"): {'name': "Alchemy", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-10-1"): {'name': "Bosch-Meiser", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-10-2"): {'name': "Beckmann Rearrangement", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-10-3"): {'name': "Stock-Pohland", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-11-1"): {'name': "Swapite", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-11-2"): {'name': "Hardening", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-11-3"): {'name': "Keying In", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "2-12-1"): {'name': "Ethane", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-12-2"): {'name': "Cyclobutane", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "2-12-3"): {'name': "Styrene", 'isResearch': 1, 'isDeterministic': 1},

    ("researchnet", "3-1-1"): {'name': "Thinner Line", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-1-2"): {'name': "Decomposition of Ethanolamine", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-1-3"): {'name': "Anesthetics", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-2-1"): {'name': "Fertigprodukt", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-2-2"): {'name': "Novel Semiconductor", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-2-3"): {'name': "Passivation", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "3-3-1"): {'name': "Life: Prep Work", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-3-2"): {'name': "Life: Cytosine", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-3-3"): {'name': "Life: Thymine", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-4-1"): {'name': "Cyanamide", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-4-2"): {'name': "Acetic Acid", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-4-3"): {'name': "Combustion Engine", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-5-1"): {'name': "Smelting Iron", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-5-2"): {'name': "Neodymium Magnet", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-5-3"): {'name': "Carbide Swap", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-6-1"): {'name': "Fuel Production", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-6-2"): {'name': "Siliconheart Piece", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-6-3"): {'name': "Raygun Mechanism", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-7-1"): {'name': "Sulfuric Acid", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-7-2"): {'name': "Fuming Nitric Acid", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-7-3"): {'name': "Rocket Fuel", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-8-1"): {'name': "Hydroxides", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-8-2"): {'name': "Nobility", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-8-3"): {'name': "Sortite", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "3-9-1"): {'name': "Radiation Treatment", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-9-2"): {'name': "Boron Compounds", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-9-3"): {'name': "Photovoltaic Cells", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-10-1"): {'name': "Elementary", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "3-10-2"): {'name': "Mixed Acids", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-10-3"): {'name': "Squaric Acid", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-11-1"): {'name': "Misproportioned", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-11-2"): {'name': "Narkotikum", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-11-3"): {'name': "Vereinheitlichung", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-12-1"): {'name': "Haber-Bosch", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "3-12-2"): {'name': "Mustard Oil", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "3-12-3"): {'name': "Nano Electric Motor", 'isResearch': 1, 'isDeterministic': 1},

    ("researchnet", "4-1-1"): {'name': "Count", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-1-2"): {'name': "Sharing is Caring", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "4-1-3"): {'name': "Reassembly", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-2-1"): {'name': "Cyanogen", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-2-2"): {'name': "Chloromethylsilane", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-2-3"): {'name': "Glyceraldehyde", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-3-1"): {'name': "Ethandiamin", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-3-2"): {'name': "Radikal", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "4-3-3"): {'name': "Kreisalkanol", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-4-1"): {'name': "Inorganic Pigments", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "4-4-2"): {'name': "Miller-Urey", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "4-4-3"): {'name': "Getting Pumped", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-5-1"): {'name': "Lewisite", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-5-2"): {'name': "Novichok", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-5-3"): {'name': "Ribulose", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-6-1"): {'name': "Knockout Drops", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-6-2"): {'name': "Strong Acids", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-6-3"): {'name': "Vitamin B3", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-7-1"): {'name': "1,2,3-Triphenol", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-7-2"): {'name': "1,3-Dimetoxibencene", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-7-3"): {'name': "Think in Spirals", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-8-1"): {'name': "Yellowcake", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "4-8-2"): {'name': "Thiourea", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-8-3"): {'name': "Downgrade", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-9-1"): {'name': "Wood Alcohol", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-9-2"): {'name': "Allyl Alcohol", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-9-3"): {'name': "Propargyl Alcohol", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-10-1"): {'name': "Condensation", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-10-2"): {'name': "Silane", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-10-3"): {'name': "Phosphine", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-11-1"): {'name': "Nuclear Medicine", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "4-11-2"): {'name': "Oxygen Supply", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-11-3"): {'name': "Red Cross", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-12-1"): {'name': "Fluoromethanes", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "4-12-2"): {'name': "Exercise", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "4-12-3"): {'name': "Nanoboxes", 'isResearch': 1, 'isDeterministic': 1},

    ("researchnet", "5-1-1"): {'name': "PAX Challenge 1", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "5-1-2"): {'name': "PAX Challenge 2", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "5-1-3"): {'name': "PAX Challenge 3", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "5-2-1"): {'name': "Fill in the Blank", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-2-2"): {'name': "Break-up", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-2-3"): {'name': "Average Out", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-3-1"): {'name': "Fake Out", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-3-2"): {'name': "Breakdown", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-3-3"): {'name': "Master of Disguise", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-4-1"): {'name': "Thermoplastic", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "5-4-2"): {'name': "Contaminated", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-4-3"): {'name': "Running Low", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-5-1"): {'name': "Not a Planet", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-5-2"): {'name': "Back to Basics", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-5-3"): {'name': "Not Helping", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-6-1"): {'name': "Two-fer", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-6-2"): {'name': "Oxygen Synthesis", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-6-3"): {'name': "Stupor", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-7-1"): {'name': "Oxygen Synthesis for Kids", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-7-2"): {'name': "+1", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-7-3"): {'name': "Nuclear Sorting", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-8-1"): {'name': "Fun with Oxides", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-8-2"): {'name': "Overflow", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-8-3"): {'name': "Conversion", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-9-1"): {'name': "Benzene Machine", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-9-2"): {'name': "Speedster", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-9-3"): {'name': "Carbon Splatter", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-10-1"): {'name': "Eth", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-10-2"): {'name': "Large Scale", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-10-3"): {'name': "Revenge", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "5-11-1"): {'name': "Excess", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-11-2"): {'name': "Carbon Compounds", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-11-3"): {'name': "Magnesium Bicarbonate", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "5-12-1"): {'name': "Impostor", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-12-2"): {'name': "Master Plan", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "5-12-3"): {'name': "Rags to Riches", 'isResearch': 0, 'isDeterministic': 0},

    ("researchnet", "6-1-1"): {'name': "Plutonium Separation", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "6-1-2"): {'name': "You're doing it wrong", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-1-3"): {'name': "Synthetic Elerium", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-2-1"): {'name': "Deadly Soft Drinks", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-2-2"): {'name': "Deadly Fluorinated Water", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-2-3"): {'name': "Deadly Microwaves", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-3-1"): {'name': "Carbon Snakes", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-3-2"): {'name': "Catalyst", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-3-3"): {'name': "Catalyst II", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-4-1"): {'name': "Unbonding with no Bonders", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "6-4-2"): {'name': "Breeder Reactor", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "6-4-3"): {'name': "Nightmare Factory", 'isResearch': 0, 'isDeterministic': 0},

    ("researchnet", "7-1-1"): {'name': "Fructose Factory", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "7-1-2"): {'name': "Misfortune Modifier", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "7-1-3"): {'name': "Particle Accelerator", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "7-2-1"): {'name': "Sun Simulator", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "7-2-2"): {'name': "100", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "7-2-3"): {'name': "Hypothetical Synthesis", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "7-3-1"): {'name': "Halogen Sorting", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "7-3-2"): {'name': "Metallica", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "7-3-3"): {'name': "Homogenizer", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "7-4-1"): {'name': "Dessication Station", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "7-4-2"): {'name': "Vinegar Distillation", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "7-4-3"): {'name': "A Glass of Water", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "7-5-1"): {'name': "Pertetroxide Synthesis", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "7-5-2"): {'name': "Fantastic Metals", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "7-5-3"): {'name': "Reppe Chemistry", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "7-6-1"): {'name': "Better Than Graphene", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "7-6-2"): {'name': "Magnets", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "7-6-3"): {'name': "Precious Oxygen", 'isResearch': 1, 'isDeterministic': 1},

    ("researchnet", "8-1-1"): {'name': "Dewer Benzene", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-1-2"): {'name': "Natural Chemo", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-1-3"): {'name': "The Chem in SpaceChem", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-2-1"): {'name': "Airborne Aldehyde", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-2-2"): {'name': "Natural Gas", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "8-2-3"): {'name': "Symmetry", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-3-1"): {'name': "Fenton Industries...", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "8-3-2"): {'name': "Oxygen Candle", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "8-3-3"): {'name': "Lies", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "8-4-1"): {'name': "Liquid Glass", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-4-2"): {'name': "PVC V", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-4-3"): {'name': "Memories", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-5-1"): {'name': "Tumbler", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "8-5-2"): {'name': "Molecular Key Carving", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "8-5-3"): {'name': "Sensitive Explosiv...", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-6-1"): {'name': "Waste Gas", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-6-2"): {'name': "Ethane Scrubbing", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "8-6-3"): {'name': "Melanophlogite Clathrates", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "8-7-1"): {'name': "Largest Prime", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-7-2"): {'name': "Three", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-7-3"): {'name': "Θne", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-8-1"): {'name': "A Small Push", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-8-2"): {'name': "Pushed Together", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-8-3"): {'name': "Repair Tungsten", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-9-1"): {'name': "Shared Space I", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-9-2"): {'name': "Shared Space II", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-9-3"): {'name': "Taking Turns", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-10-1"): {'name': "How Ionic", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-10-2"): {'name': "Two by Two", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-10-3"): {'name': "The Gold Standard", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "8-11-1"): {'name': "2 of Hearts", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-11-2"): {'name': "Miracle Cure", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-11-3"): {'name': "Oxygen Snake", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-12-1"): {'name': "That's a Relief", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-12-2"): {'name': "Headaches", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-12-3"): {'name': "Under the Counter", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-13-1"): {'name': "A New Beginning", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "8-13-2"): {'name': "Discombobulate", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "8-13-3"): {'name': "Magnum Opus", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "8-14-1"): {'name': "Organic Fusion Chemistry", 'isResearch': 1, 'isDeterministic': 0},
    ("researchnet", "8-14-2"): {'name': "The Soul of Iron", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-14-3"): {'name': "Serbalcide", 'isResearch': 1, 'isDeterministic': 1},
    ("researchnet", "8-15-1"): {'name': "Precious Tears", 'isResearch': 0, 'isDeterministic': 1},
    ("researchnet", "8-15-2"): {'name': "Desperate Measur...", 'isResearch': 0, 'isDeterministic': 0},
    ("researchnet", "8-15-3"): {'name': "Hydrocarbon Stitch", 'isResearch': 1, 'isDeterministic': 0},
}
