save2id = {

    "research-example-1": ("main", "1-1"),
    "research-tutorial-1": ("main", "1-2"),
    "research-tutorial-1point5": ("main", "1-3"),
    "research-example-2": ("main", "1-4"),
    "research-tutorial-2": ("main", "1-5"),
    "research-tutorial-3": ("main", "1-6"),

    "research-tutorial-4": ("main", "2-1"),
    "research-tutorial-5": ("main", "2-2"),
    "research-tutorial-6": ("main", "2-3"),
    "production-tutorial-1": ("main", "2-4"),
    "production-tutorial-2": ("main", "2-5"),
    "production-tutorial-3": ("main", "2-6"),

    "bonding-2": ("main", "3-1"),
    "bonding-3": ("main", "3-2"),
    "bonding-4": ("main", "3-3"),
    "bonding-6": ("main", "3-4"),
    "bonding-7": ("main", "3-5"),
    "bonding-boss": ('main', '3-6'),
    "bonding-5": ("main", "3-C"),

    "sensing-1": ("main", "4-1"),
    "sensing-2": ("main", "4-2"),
    "sensing-3": ("main", "4-3"),
    "sensing-4": ("main", "4-4"),
    "sensing-5": ("main", "4-5"),
    "sensing-boss": ('main', '4-6'),
    "sensing-6": ("main", "4-C"),
    
    "fusion-1": ("main", "5-1"),
    "fusion-2": ("main", "5-2"),
    "fusion-3": ("main", "5-3"),
    "fusion-5": ("main", "5-4"),
    "fusion-boss": ('main', '5-5'),
    "fusion-6": ("main", "5-C"),

    "mining-2": ("main", "6-1"),
    "mining-3": ("main", "6-2"),
    "mining-7": ("main", "6-3"),
    "mining-1": ("main", "6-4"),
    "mining-5": ("main", "6-6"),
    "mining-4": ("main", "6-7"),
    "mining-boss": ('main', '6-5'),
    "mining-6": ("main", "6-C"),

    "research-1": ("main", "7-1"),
    "research-3": ("main", "7-2"),
    "research-6": ("main", "7-3"),
    "research-5": ("main", "7-4"),
    "research-2": ("main", "7-5"),
    "research-boss": ('main', '7-6'),

    "organic-1": ("main", "8-1"),
    "organic-2": ("main", "8-2"),
    "organic-3": ("main", "8-3"),
    "organic-5": ("main", "8-5a"),
    "organic-6": ("main", "8-5b"),
    "organic-boss": ('main', '8-4'),

    "warp-boss": ('main', '9-1'),


    "tf2-1": ("tf2", "TF2-1"),
    "tf2-2": ("tf2", "TF2-2"),
    "tf2-3": ("tf2", "TF2-3"),


    "quantum-1": ("63corvi", "1"),
    "quantum-2": ("63corvi", "2"),
    "quantum-4": ("63corvi", "3"),
    "quantum-3": ("63corvi", "4"),
    "quantum-5": ("63corvi", "5"),
    "quantum-6": ("63corvi", "6"),
    "quantum-boss": ('63corvi', '7'),


    "published-1-1": ("researchnet", "1-1"),
    "published-1-2": ("researchnet", "1-2"),
    "published-1-3": ("researchnet", "1-3"),
    "published-2-1": ("researchnet", "2-1"),
    "published-2-2": ("researchnet", "2-2"),
    "published-2-3": ("researchnet", "2-3"),
    "published-3-1": ("researchnet", "3-1"),
    "published-3-2": ("researchnet", "3-2"),
    "published-3-3": ("researchnet", "3-3"),
    "published-4-1": ("researchnet", "4-1"),
    "published-4-2": ("researchnet", "4-2"),
    "published-4-3": ("researchnet", "4-3"),
    "published-5-1": ("researchnet", "5-1"),
    "published-5-2": ("researchnet", "5-2"),
    "published-5-3": ("researchnet", "5-3"),
    "published-6-1": ("researchnet", "6-1"),
    "published-6-2": ("researchnet", "6-2"),
    "published-6-3": ("researchnet", "6-3"),
    "published-7-1": ("researchnet", "7-1"),
    "published-7-2": ("researchnet", "7-2"),
    "published-7-3": ("researchnet", "7-3"),
    "published-8-1": ("researchnet", "8-1"),
    "published-8-2": ("researchnet", "8-2"),
    "published-8-3": ("researchnet", "8-3"),
    "published-9-1": ("researchnet", "9-1"),
    "published-9-2": ("researchnet", "9-2"),
    "published-9-3": ("researchnet", "9-3"),
    "published-10-1": ("researchnet", "10-1"),
    "published-10-2": ("researchnet", "10-2"),
    "published-10-3": ("researchnet", "10-3"),
    "published-11-1": ("researchnet", "11-1"),
    "published-11-2": ("researchnet", "11-2"),
    "published-11-3b": ("researchnet", "11-3"),
    "published-12-1": ("researchnet", "12-1"),
    "published-12-2": ("researchnet", "12-2"),
    "published-12-3": ("researchnet", "12-3"),
    
    "published-13-1": ("researchnet", "13-1"),
    "published-13-2": ("researchnet", "13-2"),
    "published-13-3": ("researchnet", "13-3"),
    "published-14-1": ("researchnet", "14-1"),
    "published-14-2": ("researchnet", "14-2"),
    "published-14-3": ("researchnet", "14-3"),
    "published-15-1": ("researchnet", "15-1"),
    "published-15-2": ("researchnet", "15-2"),
    "published-15-3": ("researchnet", "15-3"),
    "published-16-1": ("researchnet", "16-1"),
    "published-16-2": ("researchnet", "16-2"),
    "published-16-3": ("researchnet", "16-3"),
    "published-17-1": ("researchnet", "17-1"),
    "published-17-2": ("researchnet", "17-2"),
    "published-17-3": ("researchnet", "17-3"),
    "published-18-1": ("researchnet", "18-1"),
    "published-18-2": ("researchnet", "18-2"),
    "published-18-3": ("researchnet", "18-3"),
    "published-19-1": ("researchnet", "19-1"),
    "published-19-2": ("researchnet", "19-2"),
    "published-19-3": ("researchnet", "19-3"),
    "published-20-1": ("researchnet", "20-1"),
    "published-20-2": ("researchnet", "20-2"),
    "published-20-3": ("researchnet", "20-3"),
    "published-21-1": ("researchnet", "21-1"),
    "published-21-2": ("researchnet", "21-2"),
    "published-21-3": ("researchnet", "21-3"),
    "published-22-1": ("researchnet", "22-1"),
    "published-22-2": ("researchnet", "22-2"),
    "published-22-3": ("researchnet", "22-3"),
    "published-23-1": ("researchnet", "23-1"),
    "published-23-2": ("researchnet", "23-2"),
    "published-23-3": ("researchnet", "23-3"),
    "published-24-1": ("researchnet", "24-1"),
    "published-24-2": ("researchnet", "24-2"),
    "published-24-3": ("researchnet", "24-3"),
    
    "published-25-1": ("researchnet", "25-1"),
    "published-25-2": ("researchnet", "25-2"),
    "published-25-3": ("researchnet", "25-3"),
    "published-26-1": ("researchnet", "26-1"),
    "published-26-2": ("researchnet", "26-2"),
    "published-26-3": ("researchnet", "26-3"),
    "published-27-1": ("researchnet", "27-1"),
    "published-27-2": ("researchnet", "27-2"),
    "published-27-3": ("researchnet", "27-3"),
    "published-28-1": ("researchnet", "28-1"),
    "published-28-2": ("researchnet", "28-2"),
    "published-28-3": ("researchnet", "28-3"),
    "published-29-1": ("researchnet", "29-1"),
    "published-29-2": ("researchnet", "29-2"),
    "published-29-3": ("researchnet", "29-3"),
    "published-30-1": ("researchnet", "30-1"),
    "published-30-2": ("researchnet", "30-2"),
    "published-30-3": ("researchnet", "30-3"),
    "published-31-1": ("researchnet", "31-1"),
    "published-31-2": ("researchnet", "31-2"),
    "published-31-3": ("researchnet", "31-3"),
    "published-32-1": ("researchnet", "32-1"),
    "published-32-2": ("researchnet", "32-2"),
    "published-32-3": ("researchnet", "32-3"),
    "published-33-1": ("researchnet", "33-1"),
    "published-33-2": ("researchnet", "33-2"),
    "published-33-3": ("researchnet", "33-3"),
    "published-34-1": ("researchnet", "34-1"),
    "published-34-2": ("researchnet", "34-2"),
    "published-34-3": ("researchnet", "34-3"),
    "published-35-1": ("researchnet", "35-1"),
    "published-35-2": ("researchnet", "35-2"),
    "published-35-3": ("researchnet", "35-3"),
    "published-36-1": ("researchnet", "36-1"),
    "published-36-2": ("researchnet", "36-2"),
    "published-36-3": ("researchnet", "36-3"),
    
    "published-37-1": ("researchnet", "37-1"),
    "published-37-2": ("researchnet", "37-2"),
    "published-37-3": ("researchnet", "37-3"),
    "published-38-1": ("researchnet", "38-1"),
    "published-38-2": ("researchnet", "38-2"),
    "published-38-3": ("researchnet", "38-3"),
    "published-39-1": ("researchnet", "39-1"),
    "published-39-2": ("researchnet", "39-2"),
    "published-39-3": ("researchnet", "39-3"),
    "published-40-1": ("researchnet", "40-1"),
    "published-40-2": ("researchnet", "40-2"),
    "published-40-3": ("researchnet", "40-3"),
    "published-41-1": ("researchnet", "41-1"),
    "published-41-2": ("researchnet", "41-2"),
    "published-41-3": ("researchnet", "41-3"),
    "published-42-1": ("researchnet", "42-1"),
    "published-42-2": ("researchnet", "42-2"),
    "published-42-3": ("researchnet", "42-3"),
    "published-43-1": ("researchnet", "43-1"),
    "published-43-2": ("researchnet", "43-2"),
    "published-43-3": ("researchnet", "43-3"),
    "published-44-1": ("researchnet", "44-1"),
    "published-44-2": ("researchnet", "44-2"),
    "published-44-3": ("researchnet", "44-3"),
    "published-45-1": ("researchnet", "45-1"),
    "published-45-2": ("researchnet", "45-2"),
    "published-45-3": ("researchnet", "45-3"),
    "published-46-1": ("researchnet", "46-1"),
    "published-46-2": ("researchnet", "46-2"),
    "published-46-3": ("researchnet", "46-3"),
    "published-47-1": ("researchnet", "47-1"),
    "published-47-2": ("researchnet", "47-2"),
    "published-47-3": ("researchnet", "47-3"),
    "published-48-1": ("researchnet", "48-1"),
    "published-48-2": ("researchnet", "48-2"),
    "published-48-3": ("researchnet", "48-3"),
    
    "published-49-1": ("researchnet", "49-1"),
    "published-49-2": ("researchnet", "49-2"),
    "published-49-3": ("researchnet", "49-3"),
    "published-50-1": ("researchnet", "50-1"),
    "published-50-2": ("researchnet", "50-2"),
    "published-50-3": ("researchnet", "50-3"),
    "published-51-1": ("researchnet", "51-1"),
    "published-51-2": ("researchnet", "51-2"),
    "published-51-3": ("researchnet", "51-3"),
    "published-52-1": ("researchnet", "52-1"),
    "published-52-2": ("researchnet", "52-2"),
    "published-52-3": ("researchnet", "52-3"),
    "published-53-1": ("researchnet", "53-1"),
    "published-53-2": ("researchnet", "53-2"),
    "published-53-3": ("researchnet", "53-3"),
    "published-54-1": ("researchnet", "54-1"),
    "published-54-2": ("researchnet", "54-2"),
    "published-54-3": ("researchnet", "54-3"),
    "published-55-1": ("researchnet", "55-1"),
    "published-55-2": ("researchnet", "55-2"),
    "published-55-3": ("researchnet", "55-3"),
    "published-56-1": ("researchnet", "56-1"),
    "published-56-2": ("researchnet", "56-2"),
    "published-56-3": ("researchnet", "56-3"),
    "published-57-1": ("researchnet", "57-1"),
    "published-57-2": ("researchnet", "57-2"),
    "published-57-3": ("researchnet", "57-3"),
    "published-58-1": ("researchnet", "58-1"),
    "published-58-2": ("researchnet", "58-2"),
    "published-58-3": ("researchnet", "58-3"),
    "published-59-1": ("researchnet", "59-1"),
    "published-59-2": ("researchnet", "59-2"),
    "published-59-3": ("researchnet", "59-3"),
    "published-60-1": ("researchnet", "60-1"),
    "published-60-2": ("researchnet", "60-2"),
    "published-60-3": ("researchnet", "60-3"),
    
    "published-61-1": ("researchnet", "61-1"),
    "published-61-2": ("researchnet", "61-2"),
    "published-61-3": ("researchnet", "61-3"),
    "published-62-1": ("researchnet", "62-1"),
    "published-62-2": ("researchnet", "62-2"),
    "published-62-3": ("researchnet", "62-3"),
    "published-63-1": ("researchnet", "63-1"),
    "published-63-2": ("researchnet", "63-2"),
    "published-63-3": ("researchnet", "63-3"),
    "published-64-1": ("researchnet", "64-1"),
    "published-64-2": ("researchnet", "64-2"),
    "published-64-3": ("researchnet", "64-3"),

    "published-71-1": ("researchnet", "65-1"),
    "published-71-2": ("researchnet", "65-2"),
    "published-71-3": ("researchnet", "65-3"),
    "published-72-1": ("researchnet", "66-1"),
    "published-72-2": ("researchnet", "66-2"),
    "published-72-3": ("researchnet", "66-3"),
    "published-73-1": ("researchnet", "67-1"),
    "published-73-2": ("researchnet", "67-2"),
    "published-73-3": ("researchnet", "67-3"),
    "published-74-1": ("researchnet", "68-1"),
    "published-74-2": ("researchnet", "68-2"),
    "published-74-3": ("researchnet", "68-3"),
    "published-75-1": ("researchnet", "69-1"),
    "published-75-2": ("researchnet", "69-2"),
    "published-75-3": ("researchnet", "69-3"),
    "published-76-1": ("researchnet", "70-1"),
    "published-76-2": ("researchnet", "70-2"),
    "published-76-3": ("researchnet", "70-3"),

    "published-77-1": ("researchnet", "71-1"),
    "published-77-2": ("researchnet", "71-2"),
    "published-77-3": ("researchnet", "71-3"),
    "published-78-1": ("researchnet", "72-1"),
    "published-78-2": ("researchnet", "72-2"),
    "published-78-3": ("researchnet", "72-3"),
    "published-79-1": ("researchnet", "73-1"),
    "published-79-2": ("researchnet", "73-2"),
    "published-79-3": ("researchnet", "73-3"),
    "published-80-1": ("researchnet", "74-1"),
    "published-80-2": ("researchnet", "74-2"),
    "published-80-3": ("researchnet", "74-3"),
    "published-81-1": ("researchnet", "75-1"),
    "published-81-2": ("researchnet", "75-2"),
    "published-81-3": ("researchnet", "75-3"),
    "published-82-1": ("researchnet", "76-1"),
    "published-82-2": ("researchnet", "76-2"),
    "published-82-3": ("researchnet", "76-3"),
    "published-83-1": ("researchnet", "77-1"),
    "published-83-2": ("researchnet", "77-2"),
    "published-83-3": ("researchnet", "77-3"),
    "published-84-1": ("researchnet", "78-1"),
    "published-84-2": ("researchnet", "78-2"),
    "published-84-3": ("researchnet", "78-3"),
    "published-85-1": ("researchnet", "79-1"),
    "published-85-2": ("researchnet", "79-2"),
    "published-85-3": ("researchnet", "79-3"),
    "published-86-1": ("researchnet", "80-1"),
    "published-86-2": ("researchnet", "80-2"),
    "published-86-3": ("researchnet", "80-3"),
    "published-87-1": ("researchnet", "81-1"),
    "published-87-2": ("researchnet", "81-2"),
    "published-87-3": ("researchnet", "81-3"),
    "published-88-1": ("researchnet", "82-1"),
    "published-88-2": ("researchnet", "82-2"),
    "published-88-3": ("researchnet", "82-3"),
    "published-89-1": ("researchnet", "83-1"),
    "published-89-2": ("researchnet", "83-2"),
    "published-89-3": ("researchnet", "83-3"),
    "published-90-1": ("researchnet", "84-1"),
    "published-90-2": ("researchnet", "84-2"),
    "published-90-3": ("researchnet", "84-3"),
    "published-91-1": ("researchnet", "85-1"),
    "published-91-2": ("researchnet", "85-2"),
    "published-91-3": ("researchnet", "85-3"),
}

id2name = {

    ("main", "1-1"): "Of Pancakes and Spaceships",
    ("main", "1-2"): "Slightly Different",
    ("main", "1-3"): "Crossover",
    ("main", "1-4"): "An Introduction to Bonding",
    ("main", "1-5"): "A Brief History of SpaceChem",
    ("main", "1-6"): "Removing Bonds",

    ("main", "2-1"): "Double Bonds",
    ("main", "2-2"): "Best Left Unanswered",
    ("main", "2-3"): "Multiple Outputs",
    ("main", "2-4"): "An Introduction to Pipelines",
    ("main", "2-5"): "There's Something in the Fishcake",
    ("main", "2-6"): "Sleepless on Sernimir IV",

    ("main", "3-1"): "Every Day is the First Day",
    ("main", "3-2"): "It Takes Three",
    ("main", "3-3"): "Split Before Bonding",
    ("main", "3-4"): "Settling into the Routine",
    ("main", "3-5"): "Nothing Works",
    ('main', '3-6'): "A Most Unfortunate Malfunction",
    ("main", "3-C"): "Challenge: In-Place Swap",

    ("main", "4-1"): "An Introduction to Sensing",
    ("main", "4-2"): "Prelude to a Migraine",
    ("main", "4-3"): "Random Oxides",
    ("main", "4-4"): "No Ordinary Headache",
    ("main", "4-5"): "No Thanks Necessary",
    ('main', '4-6'): "No Need for Introductions",
    ("main", "4-C"): "Challenge: Going Green",

    ("main", "5-1"): "Ice to Meet You",
    ("main", "5-2"): "Under the Ice",
    ("main", "5-3"): "Unknown Sender",
    ("main", "5-4"): "Falling",
    ('main', '5-5'): "Exploding Head Syndrome",
    ("main", "5-C"): "Challenge: Applied Fusion",

    ("main", "6-1"): "Like a Boss",
    ("main", "6-2"): "Sacré Bleu!",
    ("main", "6-3"): "The Plot Thickens",
    ("main", "6-4"): "Danger Zone",
    ("main", "6-6"): "Molecular Foundry",
    ("main", "6-7"): "Gas Works Park",
    ('main', '6-5'): "More than Machine",
    ("main", "6-C"): "Challenge: KOHCTPYKTOP",

    ("main", "7-1"): "The Blue Danube",
    ("main", "7-2"): "No Stomach for Lunch",
    ("main", "7-3"): "No Employment Record Found",
    ("main", "7-4"): "Right All Along",
    ("main", "7-5"): "Accidents Happen",
    ('main', '7-6'): "Don't Fear the Reaper",

    ("main", "8-1"): "Special Assignment",
    ("main", "8-2"): "Suspicious Behavior",
    ("main", "8-3"): "I Told You So",
    ("main", "8-5a"): "Ω-Pseudoethyne",
    ("main", "8-5b"): "Σ-Ethylene",
    ('main', '8-4'): "Freedom of Choice",

    ('main', '9-1'): "End of the Line",


    ("tf2", "TF2-1"): "Moustachium 602",
    ("tf2", "TF2-2"): "Moustachium 604",
    ("tf2", "TF2-3"): "Moustachium 608",


    ("63corvi", "1"): "QT-1",
    ("63corvi", "2"): "QT-2",
    ("63corvi", "3"): "Teleporters",
    ("63corvi", "4"): "QT-3",
    ("63corvi", "5"): "QT-4",
    ("63corvi", "6"): "Precursor Compounds",
    ('63corvi', '7'): "Collapsar",


    ("researchnet", "1-1"): "Tunnels I",
    ("researchnet", "1-2"): "Tunnels II",
    ("researchnet", "1-3"): "Tunnels III",
    ("researchnet", "2-1"): "Fission I",
    ("researchnet", "2-2"): "Fission II",
    ("researchnet", "2-3"): "Fission III",
    ("researchnet", "3-1"): "Chloroform",
    ("researchnet", "3-2"): "Cycloaddition",
    ("researchnet", "3-3"): "KOHCTPYKTOP++",
    ("researchnet", "4-1"): "Quantum Decomposition",
    ("researchnet", "4-2"): "Propane Accessories",
    ("researchnet", "4-3"): "Benzoic Acid",
    ("researchnet", "5-1"): "Electrophilic Addition",
    ("researchnet", "5-2"): "Diethyl Ether",
    ("researchnet", "5-3"): "2-Hexene",
    ("researchnet", "6-1"): "Mazeite'",
    ("researchnet", "6-2"): "Silica",
    ("researchnet", "6-3"): "Galvanization",
    ("researchnet", "7-1"): "Industrial Methanol",
    ("researchnet", "7-2"): "Glyoxylic Acid",
    ("researchnet", "7-3"): "Bioplastic",
    ("researchnet", "8-1"): "Chlorination",
    ("researchnet", "8-2"): "Sulfuric Acid",
    ("researchnet", "8-3"): "Bad Times",
    ("researchnet", "9-1"): "Friedel-Crafts",
    ("researchnet", "9-2"): "Wöhler Synthesis",
    ("researchnet", "9-3"): "Diels-Alder",
    ("researchnet", "10-1"): "Bad Times, Part II",
    ("researchnet", "10-2"): "Freon",
    ("researchnet", "10-3"): "Benzene Derivation",
    ("researchnet", "11-1"): "Portland Cement",
    ("researchnet", "11-2"): "Solder Coarsening",
    ("researchnet", "11-3"): "Graphene",
    ("researchnet", "12-1"): "The Big Cleanup",
    ("researchnet", "12-2"): "Going Green Part II",
    ("researchnet", "12-3"): "Waste Treatment",
    
    ("researchnet", "13-1"): "Pyridine",
    ("researchnet", "13-2"): "Breakdown",
    ("researchnet", "13-3"): "Vitamin B3",
    ("researchnet", "14-1"): "PVC",
    ("researchnet", "14-2"): "PVA",
    ("researchnet", "14-3"): "Naphthalene",
    ("researchnet", "15-1"): "Anthraquinone",
    ("researchnet", "15-2"): "Soap",
    ("researchnet", "15-3"): "Glucose",
    ("researchnet", "16-1"): "PZA",
    ("researchnet", "16-2"): "INH",
    ("researchnet", "16-3"): "PAS",
    ("researchnet", "17-1"): "Fusion - Germane",
    ("researchnet", "17-2"): "Fusion - Silane",
    ("researchnet", "17-3"): "Fermentation",
    ("researchnet", "18-1"): "Hydrazine",
    ("researchnet", "18-2"): "Organometallics",
    ("researchnet", "18-3"): "Nonsense!",
    ("researchnet", "19-1"): "Iron and Ozone",
    ("researchnet", "19-2"): "Normalization",
    ("researchnet", "19-3"): "Decomposition",
    ("researchnet", "20-1"): "Phenol",
    ("researchnet", "20-2"): "Uracil",
    ("researchnet", "20-3"): "Pyridine",
    ("researchnet", "21-1"): "Phosgene",
    ("researchnet", "21-2"): "Ignoble",
    ("researchnet", "21-3"): "Alchemy",
    ("researchnet", "22-1"): "Bosch-Meiser",
    ("researchnet", "22-2"): "Beckmann Rearrangement",
    ("researchnet", "22-3"): "Stock-Pohland",
    ("researchnet", "23-1"): "Swapite",
    ("researchnet", "23-2"): "Hardening",
    ("researchnet", "23-3"): "Keying In",
    ("researchnet", "24-1"): "Ethane",
    ("researchnet", "24-2"): "Cyclobutane",
    ("researchnet", "24-3"): "Styrene",
    
    ("researchnet", "25-1"): "Thinner Line",
    ("researchnet", "25-2"): "Decomposition of Ethanolamine",
    ("researchnet", "25-3"): "Anesthetics",
    ("researchnet", "26-1"): "Fertigprodukt",
    ("researchnet", "26-2"): "Novel Semiconductor",
    ("researchnet", "26-3"): "Passivation",
    ("researchnet", "27-1"): "Life: Prep Work",
    ("researchnet", "27-2"): "Life: Cytosine",
    ("researchnet", "27-3"): "Life: Thymine",
    ("researchnet", "28-1"): "Cyanamide",
    ("researchnet", "28-2"): "Acetic Acid",
    ("researchnet", "28-3"): "Combustion Engine",
    ("researchnet", "29-1"): "Smelting Iron",
    ("researchnet", "29-2"): "Neodymium Magnet",
    ("researchnet", "29-3"): "Carbide Swap",
    ("researchnet", "30-1"): "Fuel Production",
    ("researchnet", "30-2"): "Siliconheart Piece",
    ("researchnet", "30-3"): "Raygun Mechanism",
    ("researchnet", "31-1"): "Sulfuric Acid",
    ("researchnet", "31-2"): "Fuming Nitric Acid",
    ("researchnet", "31-3"): "Rocket Fuel",
    ("researchnet", "32-1"): "Hydroxides",
    ("researchnet", "32-2"): "Nobility",
    ("researchnet", "32-3"): "Sortite",
    ("researchnet", "33-1"): "Radiation Treatment",
    ("researchnet", "33-2"): "Boron Compounds",
    ("researchnet", "33-3"): "Photovoltaic Cells",
    ("researchnet", "34-1"): "Elementary",
    ("researchnet", "34-2"): "Mixed Acids",
    ("researchnet", "34-3"): "Squaric Acid",
    ("researchnet", "35-1"): "Misproportioned",
    ("researchnet", "35-2"): "Narkotikum",
    ("researchnet", "35-3"): "Vereinheitlichung",
    ("researchnet", "36-1"): "Haber-Bosch",
    ("researchnet", "36-2"): "Mustard Oil",
    ("researchnet", "36-3"): "Nano Electric Motor",
    
    ("researchnet", "37-1"): "Count",
    ("researchnet", "37-2"): "Sharing is Caring",
    ("researchnet", "37-3"): "Reassembly",
    ("researchnet", "38-1"): "Cyanogen",
    ("researchnet", "38-2"): "Chloromethylsilane",
    ("researchnet", "38-3"): "Glyceraldehyde",
    ("researchnet", "39-1"): "Ethandiamin",
    ("researchnet", "39-2"): "Radikal",
    ("researchnet", "39-3"): "Kreisalkanol",
    ("researchnet", "40-1"): "Inorganic Pigments",
    ("researchnet", "40-2"): "Miller-Urey",
    ("researchnet", "40-3"): "Getting Pumped",
    ("researchnet", "41-1"): "Lewisite",
    ("researchnet", "41-2"): "Novichok",
    ("researchnet", "41-3"): "Ribulose",
    ("researchnet", "42-1"): "Knockout Drops",
    ("researchnet", "42-2"): "Strong Acids",
    ("researchnet", "42-3"): "Vitamin B3",
    ("researchnet", "43-1"): "1,2,3-Triphenol",
    ("researchnet", "43-2"): "1,3-Dimetoxibencene",
    ("researchnet", "43-3"): "Think in Spirals",
    ("researchnet", "44-1"): "Yellowcake",
    ("researchnet", "44-2"): "Thiourea",
    ("researchnet", "44-3"): "Downgrade",
    ("researchnet", "45-1"): "Wood Alcohol",
    ("researchnet", "45-2"): "Allyl Alcohol",
    ("researchnet", "45-3"): "Propargyl Alcohol",
    ("researchnet", "46-1"): "Condensation",
    ("researchnet", "46-2"): "Silane",
    ("researchnet", "46-3"): "Phosphine",
    ("researchnet", "47-1"): "Nuclear Medicine",
    ("researchnet", "47-2"): "Oxygen Supply",
    ("researchnet", "47-3"): "Red Cross",
    ("researchnet", "48-1"): "Fluoromethanes",
    ("researchnet", "48-2"): "Exercise",
    ("researchnet", "48-3"): "Nanoboxes",
    
    ("researchnet", "49-1"): "PAX Challenge 1",
    ("researchnet", "49-2"): "PAX Challenge 2",
    ("researchnet", "49-3"): "PAX Challenge 3",
    ("researchnet", "50-1"): "Fill in the Blank",
    ("researchnet", "50-2"): "Break-up",
    ("researchnet", "50-3"): "Average Out",
    ("researchnet", "51-1"): "Fake Out",
    ("researchnet", "51-2"): "Breakdown",
    ("researchnet", "51-3"): "Master of Disguise",
    ("researchnet", "52-1"): "Thermoplastic",
    ("researchnet", "52-2"): "Contaminated",
    ("researchnet", "52-3"): "Running Low",
    ("researchnet", "53-1"): "Not a Planet",
    ("researchnet", "53-2"): "Back to Basics",
    ("researchnet", "53-3"): "Not Helping",
    ("researchnet", "54-1"): "Two-fer",
    ("researchnet", "54-2"): "Oxygen Synthesis",
    ("researchnet", "54-3"): "Stupor",
    ("researchnet", "55-1"): "Oxygen Synthesis for Kids",
    ("researchnet", "55-2"): "+1",
    ("researchnet", "55-3"): "Nuclear Sorting",
    ("researchnet", "56-1"): "Fun with Oxides",
    ("researchnet", "56-2"): "Overflow",
    ("researchnet", "56-3"): "Conversion",
    ("researchnet", "57-1"): "Benzene Machine",
    ("researchnet", "57-2"): "Speedster",
    ("researchnet", "57-3"): "Carbon Splatter",
    ("researchnet", "58-1"): "Eth",
    ("researchnet", "58-2"): "Large Scale",
    ("researchnet", "58-3"): "Revenge",
    ("researchnet", "59-1"): "Excess",
    ("researchnet", "59-2"): "Carbon Compounds",
    ("researchnet", "59-3"): "Magnesium Bicarbonate",
    ("researchnet", "60-1"): "Impostor",
    ("researchnet", "60-2"): "Master Plan",
    ("researchnet", "60-3"): "Rags to Riches",
    
    ("researchnet", "61-1"): "Plutonium Separator",
    ("researchnet", "61-2"): "You're doing it wrong",
    ("researchnet", "61-3"): "Synthetic Elerium",
    ("researchnet", "62-1"): "Deadly Soft Drinks",
    ("researchnet", "62-2"): "Deadly Fluorinate...",
    ("researchnet", "62-3"): "Deadly Microwaves",
    ("researchnet", "63-1"): "Carbon Snakes",
    ("researchnet", "63-2"): "Catalyst",
    ("researchnet", "63-3"): "Catalyst II",
    ("researchnet", "64-1"): "Unbonding with n...",
    ("researchnet", "64-2"): "Breeder Reactor",
    ("researchnet", "64-3"): "Nightmare Factory",

    ("researchnet", "65-1"): "Fructose Factory",
    ("researchnet", "65-2"): "Misfortune Modifier",
    ("researchnet", "65-3"): "Particle Accelerator",
    ("researchnet", "66-1"): "Sun Simulator",
    ("researchnet", "66-2"): "100",
    ("researchnet", "66-3"): "Hypothetical Synthesis",
    ("researchnet", "67-1"): "Halogen Sorting",
    ("researchnet", "67-2"): "Metallica",
    ("researchnet", "67-3"): "Homogenizer",
    ("researchnet", "68-1"): "Dessication Station",
    ("researchnet", "68-2"): "Vinegar Distillation",
    ("researchnet", "68-3"): "A Glass of Water",
    ("researchnet", "69-1"): "Pertetroxide Synthesis",
    ("researchnet", "69-2"): "Fantastic Metals",
    ("researchnet", "69-3"): "Reppe Chemistry",
    ("researchnet", "70-1"): "Better Than Graphene",
    ("researchnet", "70-2"): "Magnets",
    ("researchnet", "70-3"): "Precious Oxygen",

    ("researchnet", "71-1"): "Dewer Benzene",
    ("researchnet", "71-2"): "Natural Chemo",
    ("researchnet", "71-3"): "The Chem in Spac...",
    ("researchnet", "72-1"): "Airborne Aldehyde",
    ("researchnet", "72-2"): "Natural Gas",
    ("researchnet", "72-3"): "Symmetry",
    ("researchnet", "73-1"): "Fenton Industries...",
    ("researchnet", "73-2"): "Oxygen Candle",
    ("researchnet", "73-3"): "Lies",
    ("researchnet", "74-1"): "Liquid Glass",
    ("researchnet", "74-2"): "PVC V",
    ("researchnet", "74-3"): "Memories",
    ("researchnet", "75-1"): "Tumbler",
    ("researchnet", "75-2"): "Molecular Key Car...",
    ("researchnet", "75-3"): "Sensitive Explosiv...",
    ("researchnet", "76-1"): "Waste Gas",
    ("researchnet", "76-2"): "Ethane Scrubbing",
    ("researchnet", "76-3"): "Melanophlogite Cla...",
    ("researchnet", "77-1"): "Largest Prime",
    ("researchnet", "77-2"): "Three",
    ("researchnet", "77-3"): "Θne",
    ("researchnet", "78-1"): "A Small Push",
    ("researchnet", "78-2"): "Pushed Together",
    ("researchnet", "78-3"): "Repair Tungsten",
    ("researchnet", "79-1"): "Shared Space I",
    ("researchnet", "79-2"): "Shared Space II",
    ("researchnet", "79-3"): "Taking Turns",
    ("researchnet", "80-1"): "How Ionic",
    ("researchnet", "80-2"): "Two by Two",
    ("researchnet", "80-3"): "The Gold Standard",
    ("researchnet", "81-1"): "2 of Hearts",
    ("researchnet", "81-2"): "Miracle Cure",
    ("researchnet", "81-3"): "Oxygen Snake",
    ("researchnet", "82-1"): "That's a Relief",
    ("researchnet", "82-2"): "Headaches",
    ("researchnet", "82-3"): "Under the Counter",
    ("researchnet", "83-1"): "A New Beginning",
    ("researchnet", "83-2"): "Discombobulate",
    ("researchnet", "83-3"): "Magnum Opus",
    ("researchnet", "84-1"): "Organic Fusion Ch...",
    ("researchnet", "84-2"): "The Soul of Iron",
    ("researchnet", "84-3"): "Serbalcide",
    ("researchnet", "85-1"): "Precious Tears",
    ("researchnet", "85-2"): "Desperate Measur...",
    ("researchnet", "85-3"): "Hydrocarbon Stitch",
}
