save_names_dict = {

    "research-example-1": ("main", "1-1", "Of Pancakes and Spaceships"),
    "research-tutorial-1": ("main", "1-2", "Slightly Different"),
    "research-tutorial-1point5": ("main", "1-3", "Crossover"),
    "research-example-2": ("main", "1-4", "An Introduction to Bonding"),
    "research-tutorial-2": ("main", "1-5", "A Brief History of SpaceChem"),
    "research-tutorial-3": ("main", "1-6", "Removing Bonds"),

    "research-tutorial-4": ("main", "2-1", "Double Bonds"),
    "research-tutorial-5": ("main", "2-2", "Best Left Unanswered"),
    "research-tutorial-6": ("main", "2-3", "Multiple Outputs"),
    "production-tutorial-1": ("main", "2-4", "An Introduction to Pipelines"),
    "production-tutorial-2": ("main", "2-5", "There's Something in the Fishcake"),
    "production-tutorial-3": ("main", "2-6", "Sleepless on Sernimir IV"),

    "bonding-2": ("main", "3-1", "Every Day is the First Day"),
    "bonding-3": ("main", "3-2", "It Takes Three"),
    "bonding-4": ("main", "3-3", "Split Before Bonding"),
    "bonding-6": ("main", "3-4", "Settling into the Routine"),
    "bonding-7": ("main", "3-5", "Nothing Works"),
    "bonding-5": ("main", "3-C", "Challenge: In-Place Swap"),

    "sensing-1": ("main", "4-1", "An Introduction to Sensing"),
    "sensing-2": ("main", "4-2", "Prelude to a Migraine"),
    "sensing-3": ("main", "4-3", "Random Oxides"),
    "sensing-4": ("main", "4-4", "No Ordinary Headache"),
    "sensing-5": ("main", "4-5", "No Thanks Necessary"),
    "sensing-6": ("main", "4-C", "Challenge: Going Green"),

    "fusion-1": ("main", "5-1", "Ice to Meet You"),
    "fusion-2": ("main", "5-2", "Under the Ice"),
    "fusion-3": ("main", "5-3", "Unknown Sender"),
    "fusion-5": ("main", "5-4", "Falling"),
    "fusion-6": ("main", "5-C", "Challenge: Applied Fusion"),

    "mining-2": ("main", "6-1", "Like a Boss"),
    "mining-3": ("main", "6-2", "Sacré Bleu!"),
    "mining-7": ("main", "6-3", "The Plot Thickens"),
    "mining-1": ("main", "6-4", "Danger Zone"),
    "mining-5": ("main", "6-6", "Molecular Foundry"),
    "mining-4": ("main", "6-7", "Gas Works Park"),
    "mining-6": ("main", "6-C", "Challenge: KOHCTPYKTOP"),

    "research-1": ("main", "7-1", "The Blue Danube"),
    "research-3": ("main", "7-2", "No Stomach for Lunch"),
    "research-6": ("main", "7-3", "No Employment Record Found"),
    "research-5": ("main", "7-4", "Right All Along"),
    "research-2": ("main", "7-5", "Accidents Happen"),

    "organic-1": ("main", "8-1", "Special Assignment"),
    "organic-2": ("main", "8-2", "Suspicious Behavior"),
    "organic-3": ("main", "8-3", "I Told You So"),
    "organic-5": ("main", "8-5a", "Ω-Pseudoethyne"),
    "organic-6": ("main", "8-5b", "Σ-Ethylene"),


    "tf2-1": ("tf2", "TF2-1", "Moustachium 602"),
    "tf2-2": ("tf2", "TF2-2", "Moustachium 604"),
    "tf2-3": ("tf2", "TF2-3", "Moustachium 608"),

    "quantum-1": ("63corvi", "1", "QT-1"),
    "quantum-2": ("63corvi", "2", "QT-2"),
    "quantum-4": ("63corvi", "3", "Teleporters"),
    "quantum-3": ("63corvi", "4", "QT-3"),
    "quantum-5": ("63corvi", "5", "QT-4"),
    "quantum-6": ("63corvi", "6", "Precursor Compounds"),

    "published-1-1": ("researchnet", "1-1", "Tunnels I"),
    "published-1-2": ("researchnet", "1-2", "Tunnels II"),
    "published-1-3": ("researchnet", "1-3", "Tunnels III"),
    "published-2-1": ("researchnet", "2-1", "Fission I"),
    "published-2-2": ("researchnet", "2-2", "Fission II"),
    "published-2-3": ("researchnet", "2-3", "Fission III"),
    "published-3-1": ("researchnet", "3-1", "Chloroform"),
    "published-3-2": ("researchnet", "3-2", "Cycloaddition"),
    "published-3-3": ("researchnet", "3-3", "KOHCTPYKTOP++"),
    "published-4-1": ("researchnet", "4-1", "Quantum Decomposition"),
    "published-4-2": ("researchnet", "4-2", "Propane Accessories"),
    "published-4-3": ("researchnet", "4-3", "Benzoic Acid"),
    "published-5-1": ("researchnet", "5-1", "Electrophilic Addition"),
    "published-5-2": ("researchnet", "5-2", "Diethyl Ether"),
    "published-5-3": ("researchnet", "5-3", "2-Hexene"),
    "published-6-1": ("researchnet", "6-1", "Mazeite'"),
    "published-6-2": ("researchnet", "6-2", "Silica"),
    "published-6-3": ("researchnet", "6-3", "Galvanization"),
    "published-7-1": ("researchnet", "7-1", "Industrial Methanol"),
    "published-7-2": ("researchnet", "7-2", "Glyoxylic Acid"),
    "published-7-3": ("researchnet", "7-3", "Bioplastic"),
    "published-8-1": ("researchnet", "8-1", "Chlorination"),
    "published-8-2": ("researchnet", "8-2", "Sulfuric Acid"),
    "published-8-3": ("researchnet", "8-3", "Bad Times"),
    "published-9-1": ("researchnet", "9-1", "Friedel-Crafts"),
    "published-9-2": ("researchnet", "9-2", "Wöhler Synthesis"),
    "published-9-3": ("researchnet", "9-3", "Diels-Alder"),
    "published-10-1": ("researchnet", "10-1", "Bad Times, Part II"),
    "published-10-2": ("researchnet", "10-2", "Freon"),
    "published-10-3": ("researchnet", "10-3", "Benzene Derivation"),
    "published-11-1": ("researchnet", "11-1", "Portland Cement"),
    "published-11-2": ("researchnet", "11-2", "Solder Coarsening"),
    "published-11-3b": ("researchnet", "11-3", "Graphene"),
    "published-12-1": ("researchnet", "12-1", "The Big Cleanup"),
    "published-12-2": ("researchnet", "12-2", "Going Green Part II"),
    "published-12-3": ("researchnet", "12-3", "Waste Treatment"),
    
    "published-13-1": ("researchnet", "13-1", "Pyridine"),
    "published-13-2": ("researchnet", "13-2", "Breakdown"),
    "published-13-3": ("researchnet", "13-3", "Vitamin B3"),
    "published-14-1": ("researchnet", "14-1", "PVC"),
    "published-14-2": ("researchnet", "14-2", "PVA"),
    "published-14-3": ("researchnet", "14-3", "Naphthalene"),
    "published-15-1": ("researchnet", "15-1", "Anthraquinone"),
    "published-15-2": ("researchnet", "15-2", "Soap"),
    "published-15-3": ("researchnet", "15-3", "Glucose"),
    "published-16-1": ("researchnet", "16-1", "PZA"),
    "published-16-2": ("researchnet", "16-2", "INH"),
    "published-16-3": ("researchnet", "16-3", "PAS"),
    "published-17-1": ("researchnet", "17-1", "Fusion - Germane"),
    "published-17-2": ("researchnet", "17-2", "Fusion - Silane"),
    "published-17-3": ("researchnet", "17-3", "Fermentation"),
    "published-18-1": ("researchnet", "18-1", "Hydrazine"),
    "published-18-2": ("researchnet", "18-2", "Organometallics"),
    "published-18-3": ("researchnet", "18-3", "Nonsense!"),
    "published-19-1": ("researchnet", "19-1", "Iron and Ozone"),
    "published-19-2": ("researchnet", "19-2", "Normalization"),
    "published-19-3": ("researchnet", "19-3", "Decomposition"),
    "published-20-1": ("researchnet", "20-1", "Phenol"),
    "published-20-2": ("researchnet", "20-2", "Uracil"),
    "published-20-3": ("researchnet", "20-3", "Pyridine"),
    "published-21-1": ("researchnet", "21-1", "Phosgene"),
    "published-21-2": ("researchnet", "21-2", "Ignoble"),
    "published-21-3": ("researchnet", "21-3", "Alchemy"),
    "published-22-1": ("researchnet", "22-1", "Bosch-Meiser"),
    "published-22-2": ("researchnet", "22-2", "Beckmann Rearrangement"),
    "published-22-3": ("researchnet", "22-3", "Stock-Pohland"),
    "published-23-1": ("researchnet", "23-1", "Swapite"),
    "published-23-2": ("researchnet", "23-2", "Hardening"),
    "published-23-3": ("researchnet", "23-3", "Keying in"),
    "published-24-1": ("researchnet", "24-1", "Ethane"),
    "published-24-2": ("researchnet", "24-2", "Cyclobutane"),
    "published-24-3": ("researchnet", "24-3", "Styrene"),
    
    "published-25-1": ("researchnet", "25-1", "Thinner Line"),
    "published-25-2": ("researchnet", "25-2", "Decomposition of Ethanolamine"),
    "published-25-3": ("researchnet", "25-3", "Anesthetics"),
    "published-26-1": ("researchnet", "26-1", "Fertigprodukt"),
    "published-26-2": ("researchnet", "26-2", "Novel Semiconductors"),
    "published-26-3": ("researchnet", "26-3", "Passivation"),
    "published-27-1": ("researchnet", "27-1", "Life: Prep work"),
    "published-27-2": ("researchnet", "27-2", "Life: Cytosine"),
    "published-27-3": ("researchnet", "27-3", "Life: Thymine"),
    "published-28-1": ("researchnet", "28-1", "Cyanamide"),
    "published-28-2": ("researchnet", "28-2", "Acetic Acid"),
    "published-28-3": ("researchnet", "28-3", "Combustion Engine"),
    "published-29-1": ("researchnet", "29-1", "Smelting Iron"),
    "published-29-2": ("researchnet", "29-2", "Neodymium Magnet"),
    "published-29-3": ("researchnet", "29-3", "Carbide Swap"),
    "published-30-1": ("researchnet", "30-1", "Fuel Production"),
    "published-30-2": ("researchnet", "30-2", "Siliconheart Piece"),
    "published-30-3": ("researchnet", "30-3", "Raygun Mechanism"),
    "published-31-1": ("researchnet", "31-1", "Sulfuric Acid"),
    "published-31-2": ("researchnet", "31-2", "Fuming Nitric Acid"),
    "published-31-3": ("researchnet", "31-3", "Rocket Fuel"),
    "published-32-1": ("researchnet", "32-1", "Hydroxides"),
    "published-32-2": ("researchnet", "32-2", "Nobility"),
    "published-32-3": ("researchnet", "32-3", "Sortite"),
    "published-33-1": ("researchnet", "33-1", "Radiation Treatment"),
    "published-33-2": ("researchnet", "33-2", "Boron Compounds"),
    "published-33-3": ("researchnet", "33-3", "Photovoltaic Cells"),
    "published-34-1": ("researchnet", "34-1", "Elementary"),
    "published-34-2": ("researchnet", "34-2", "Mixed Acids"),
    "published-34-3": ("researchnet", "34-3", "Squaric Acid"),
    "published-35-1": ("researchnet", "35-1", "Misproportioned"),
    "published-35-2": ("researchnet", "35-2", "Narkotikum"),
    "published-35-3": ("researchnet", "35-3", "Vereinheitlichung"),
    "published-36-1": ("researchnet", "36-1", "Haber-Bosch"),
    "published-36-2": ("researchnet", "36-2", "Mustard Oil"),
    "published-36-3": ("researchnet", "36-3", "Nano Electric Motor"),
    
    "published-37-1": ("researchnet", "37-1", "Count"),
    "published-37-2": ("researchnet", "37-2", "Sharing is Caring"),
    "published-37-3": ("researchnet", "37-3", "Reassembly"),
    "published-38-1": ("researchnet", "38-1", "Cyanogen"),
    "published-38-2": ("researchnet", "38-2", "Chloromethylsilane"),
    "published-38-3": ("researchnet", "38-3", "Glyceraldehyde"),
    "published-39-1": ("researchnet", "39-1", "Ethandiamin"),
    "published-39-2": ("researchnet", "39-2", "Radikal"),
    "published-39-3": ("researchnet", "39-3", "Kreisalkanol"),
    "published-40-1": ("researchnet", "40-1", "Inorganic Pigments"),
    "published-40-2": ("researchnet", "40-2", "Miller-Urey"),
    "published-40-3": ("researchnet", "40-3", "Getting Pumped"),
    "published-41-1": ("researchnet", "41-1", "Lewisite"),
    "published-41-2": ("researchnet", "41-2", "Novichok"),
    "published-41-3": ("researchnet", "41-3", "Ribulose"),
    "published-42-1": ("researchnet", "42-1", "Knockout Drops"),
    "published-42-2": ("researchnet", "42-2", "Strong Acids"),
    "published-42-3": ("researchnet", "42-3", "Vitamin B3"),
    "published-43-1": ("researchnet", "43-1", "1,2,3-Triphenol"),
    "published-43-2": ("researchnet", "43-2", "1,3-Dimetoxibencene"),
    "published-43-3": ("researchnet", "43-3", "Think in Spirals"),
    "published-44-1": ("researchnet", "44-1", "Yellowcake"),
    "published-44-2": ("researchnet", "44-2", "Thiourea"),
    "published-44-3": ("researchnet", "44-3", "Downgrade"),
    "published-45-1": ("researchnet", "45-1", "Wood Alcohol"),
    "published-45-2": ("researchnet", "45-2", "Allyl Alcohol"),
    "published-45-3": ("researchnet", "45-3", "Propargyl Alcohol"),
    "published-46-1": ("researchnet", "46-1", "Condensation"),
    "published-46-2": ("researchnet", "46-2", "Silane"),
    "published-46-3": ("researchnet", "46-3", "Phosphine"),
    "published-47-1": ("researchnet", "47-1", "Nuclear Medicine"),
    "published-47-2": ("researchnet", "47-2", "Oxygen Supply"),
    "published-47-3": ("researchnet", "47-3", "Red Cross"),
    "published-48-1": ("researchnet", "48-1", "Fluoromethanes"),
    "published-48-2": ("researchnet", "48-2", "Exercise"),
    "published-48-3": ("researchnet", "48-3", "Nanoboxes"),
    
    "published-49-1": ("researchnet", "49-1", "PAX Challenge 1"),
    "published-49-2": ("researchnet", "49-2", "PAX Challenge 2"),
    "published-49-3": ("researchnet", "49-3", "PAX Challenge 3"),
    "published-50-1": ("researchnet", "50-1", "Fill in the Blank"),
    "published-50-2": ("researchnet", "50-2", "Break-up"),
    "published-50-3": ("researchnet", "50-3", "Average Out"),
    "published-51-1": ("researchnet", "51-1", "Fake Out"),
    "published-51-2": ("researchnet", "51-2", "Breakdown"),
    "published-51-3": ("researchnet", "51-3", "Master of Disguise"),
    "published-52-1": ("researchnet", "52-1", "Thermoplastic"),
    "published-52-2": ("researchnet", "52-2", "Contaminated"),
    "published-52-3": ("researchnet", "52-3", "Running Low"),
    "published-53-1": ("researchnet", "53-1", "Not a Planet"),
    "published-53-2": ("researchnet", "53-2", "Back to Basics"),
    "published-53-3": ("researchnet", "53-3", "Not Helping"),
    "published-54-1": ("researchnet", "54-1", "Two-fer"),
    "published-54-2": ("researchnet", "54-2", "Oxygen Synthesis"),
    "published-54-3": ("researchnet", "54-3", "Stupor"),
    "published-55-1": ("researchnet", "55-1", "Oxygen Synthesis for Kids"),
    "published-55-2": ("researchnet", "55-2", "+1"),
    "published-55-3": ("researchnet", "55-3", "Nuclear Sorting"),
    "published-56-1": ("researchnet", "56-1", "Fun with Oxides"),
    "published-56-2": ("researchnet", "56-2", "Overflow"),
    "published-56-3": ("researchnet", "56-3", "Conversion"),
    "published-57-1": ("researchnet", "57-1", "Benzene Machine"),
    "published-57-2": ("researchnet", "57-2", "Speedster"),
    "published-57-3": ("researchnet", "57-3", "Carbon Splatter"),
    "published-58-1": ("researchnet", "58-1", "Eth"),
    "published-58-2": ("researchnet", "58-2", "Large Scale"),
    "published-58-3": ("researchnet", "58-3", "Revenge"),
    "published-59-1": ("researchnet", "59-1", "Excess"),
    "published-59-2": ("researchnet", "59-2", "Carbon Compounds"),
    "published-59-3": ("researchnet", "59-3", "Magnesium Bicarbonate"),
    "published-60-1": ("researchnet", "60-1", "Impostor"),
    "published-60-2": ("researchnet", "60-2", "Master Plan"),
    "published-60-3": ("researchnet", "60-3", "Rags to Riches"),
    
    "published-61-1": ("researchnet", "61-1", "Plutonium Separator"),
    "published-61-2": ("researchnet", "61-2", "You're doing it wrong"),
    "published-61-3": ("researchnet", "61-3", "Synthetic Elerium"),
    "published-62-1": ("researchnet", "62-1", "Deadly Soft Drinks"),
    "published-62-2": ("researchnet", "62-2", "Deadly Fluorinate..."),
    "published-62-3": ("researchnet", "62-3", "Deadly Microwaves"),
    "published-63-1": ("researchnet", "63-1", "Carbon Snakes"),
    "published-63-2": ("researchnet", "63-2", "Catalyst"),
    "published-63-3": ("researchnet", "63-3", "Catalyst II"),
    "published-64-1": ("researchnet", "64-1", "Unbonding with n..."),
    "published-64-2": ("researchnet", "64-2", "Breeder Reactor"),
    "published-64-3": ("researchnet", "64-3", "Nightmare Factory"),

    "published-71-1": ("researchnet", "65-1", "Fructose Factory"),
    "published-71-2": ("researchnet", "65-2", "Misfortune Modifier"),
    "published-71-3": ("researchnet", "65-3", "Particle Accelerator"),
    "published-72-1": ("researchnet", "66-1", "Sun Simulator"),
    "published-72-2": ("researchnet", "66-2", "100"),
    "published-72-3": ("researchnet", "66-3", "Hypothetical Synthesis"),
    "published-73-1": ("researchnet", "67-1", "Halogen Sorting"),
    "published-73-2": ("researchnet", "67-2", "Metallica"),
    "published-73-3": ("researchnet", "67-3", "Homogenizer"),
    "published-74-1": ("researchnet", "68-1", "Dessication Station"),
    "published-74-2": ("researchnet", "68-2", "Vinegar Distillation"),
    "published-74-3": ("researchnet", "68-3", "A Glass of Water"),
    "published-75-1": ("researchnet", "69-1", "Pertetroxide Synthesis"),
    "published-75-2": ("researchnet", "69-2", "Fantastic Metals"),
    "published-75-3": ("researchnet", "69-3", "Reppe Chemistry"),
    "published-76-1": ("researchnet", "70-1", "Better Than Graphene"),
    "published-76-2": ("researchnet", "70-2", "Magnets"),
    "published-76-3": ("researchnet", "70-3", "Precious Oxygen"),

    "published-77-1": ("researchnet", "71-1", "Dewer Benzene"),
    "published-77-2": ("researchnet", "71-2", "Natural Chemo"),
    "published-77-3": ("researchnet", "71-3", "The Chem in Spac..."),
    "published-78-1": ("researchnet", "72-1", "Airborne Aldehyde"),
    "published-78-2": ("researchnet", "72-2", "Natural Gas"),
    "published-78-3": ("researchnet", "72-3", "Symmetry"),
    "published-79-1": ("researchnet", "73-1", "Fenton Industries..."),
    "published-79-2": ("researchnet", "73-2", "Oxygen Candle"),
    "published-79-3": ("researchnet", "73-3", "Lies"),
    "published-80-1": ("researchnet", "74-1", "Liquid Glass"),
    "published-80-2": ("researchnet", "74-2", "PVC V"),
    "published-80-3": ("researchnet", "74-3", "Memories"),
    "published-81-1": ("researchnet", "75-1", "Tumbler"),
    "published-81-2": ("researchnet", "75-2", "Molecular Key Car..."),
    "published-81-3": ("researchnet", "75-3", "Sensitive Explosiv..."),
    "published-82-1": ("researchnet", "76-1", "Waste Gas"),
    "published-82-2": ("researchnet", "76-2", "Ethane Scrubbing"),
    "published-82-3": ("researchnet", "76-3", "Melanophlogite Cla..."),
    "published-83-1": ("researchnet", "77-1", "Largest Prime"),
    "published-83-2": ("researchnet", "77-2", "Three"),
    "published-83-3": ("researchnet", "77-3", "Θne"),
    "published-84-1": ("researchnet", "78-1", "A Small Push"),
    "published-84-2": ("researchnet", "78-2", "Pushed Together"),
    "published-84-3": ("researchnet", "78-3", "Repair Tungsten"),
    "published-85-1": ("researchnet", "79-1", "Shared Space I"),
    "published-85-2": ("researchnet", "79-2", "Shared Space II"),
    "published-85-3": ("researchnet", "79-3", "Taking Turns"),
    "published-86-1": ("researchnet", "80-1", "How Ionic"),
    "published-86-2": ("researchnet", "80-2", "Two by Two"),
    "published-86-3": ("researchnet", "80-3", "The Gold Standard"),
    "published-87-1": ("researchnet", "81-1", "2 of Hearts"),
    "published-87-2": ("researchnet", "81-2", "Miracle Cure"),
    "published-87-3": ("researchnet", "81-3", "Oxygen Snake"),
    "published-88-1": ("researchnet", "82-1", "That's a Relief"),
    "published-88-2": ("researchnet", "82-2", "Headaches"),
    "published-88-3": ("researchnet", "82-3", "Under the Counter"),
    "published-89-1": ("researchnet", "83-1", "A New Beginning"),
    "published-89-2": ("researchnet", "83-2", "Discombobulate"),
    "published-89-3": ("researchnet", "83-3", "Magnum Opus"),
    "published-90-1": ("researchnet", "84-1", "Organic Fusion Ch..."),
    "published-90-2": ("researchnet", "84-2", "The Soul of Iron"),
    "published-90-3": ("researchnet", "84-3", "Serbalcide"),
    "published-91-1": ("researchnet", "85-1", "Precious Tears"),
    "published-91-2": ("researchnet", "85-2", "Desperate Measur..."),
    "published-91-3": ("researchnet", "85-3", "Hydrocarbon Stitch")
}
