# cat - | grep -P 'Windows|Linux'|sed -e "s/^/    \'/g"|sed -e "s/\t/\': \'/g"|sed -e "s/$/\',/g"

user2OS = {
    
    '12345ieee': 'Linux',
    'Andy': 'Windows',
    'ants280': 'Windows',
    'Bashy_McFetus': 'Windows',
    'Benjikshoo': 'Linux',
    'Blueeyedrat': 'Windows',
    'CaitSith2': 'Windows',
    'cams': 'Windows',
    'Carlbunk': 'Windows',
    'cearn': 'Windows',
    'DariusRaider': 'Windows',
    'davenger': 'Windows',
    'DFyNt2U': 'Windows',
    'ecco2': 'Windows',
    'Elvis': 'Windows',
    'gggol': 'Linux',
    'goodbyeclock': 'Windows',
    'goshisanniichi': 'Windows',
    'GuavaMoment': 'Windows',
    'hailstone': 'Windows',
    'Ir_Sigma': 'Windows',
    'Iridium': 'Windows',
    'joequincy': 'Windows',
    'keyyek': 'Windows',
    'Krackor': 'Windows',
    'Leylite': 'Linux',
    'MestreLion': 'Linux',
    'michelcolman': 'Linux',
    'mrcable': 'Windows',
    'pieceofmind': 'Windows',
    'q00u': 'Windows',
    'RYANSUPERGENIUS1123': 'Windows',
    'Sahishar': 'Windows',
    'ShadowTheAge': 'Windows',
    'SnapDragon': 'Windows',
    'Sniper_John_Uk': 'Windows',
    'Steve42': 'Windows',
    'testalot47': 'Windows',
    'toi333': 'Windows',
    'TotalSushi': 'Windows',
    'ToughThought': 'Linux',
    'whoever314': 'Windows',
    'WildFilch': 'Linux',
    'WildM': 'Windows',
    'WolfWings': 'Windows',
    'Zemyla': 'Windows',
    'Zig': 'Windows',

}
